import { getChapter } from '../catalog'
import { mc, multi, numeric } from '../make'
import type { ChapterContent } from '../../lib/types'

const meta = getChapter(4)!

export const chapter04: ChapterContent = {
  meta,
  theory: {
    goal: 'Use fractions fluently: write them in simplest form, move between mixed numbers and improper fractions, and calculate with all four operations, including fractions of amounts.',
    youNeedFirst: [
      'Times tables up to $12 \\times 12$',
      'Finding a highest common factor (HCF)',
      'The idea that a fraction is a part of a whole',
    ],
    keyFacts: [
      {
        title: 'Equivalent fractions',
        body: 'Multiply or divide the numerator and the denominator by the **same** number. $\\dfrac{2}{5} = \\dfrac{4}{10} = \\dfrac{8}{20}$.',
      },
      {
        title: 'Simplest form',
        body: 'Divide both parts by the HCF. $\\dfrac{18}{24} = \\dfrac{3}{4}$ because the HCF of 18 and 24 is 6.',
      },
      {
        title: 'Mixed and improper',
        body: '$3\\dfrac{1}{4} = \\dfrac{13}{4}$ because $3 \\times 4 + 1 = 13$. To convert back, divide 13 by 4: 3 remainder 1.',
      },
      {
        title: 'Add and subtract',
        body: 'Use a common denominator. $\\dfrac{2}{3} + \\dfrac{1}{6} = \\dfrac{4}{6} + \\dfrac{1}{6} = \\dfrac{5}{6}$. Never add the denominators.',
      },
      {
        title: 'Multiply',
        body: 'Multiply numerators, multiply denominators, then simplify. $\\dfrac{2}{3} \\times \\dfrac{5}{7} = \\dfrac{10}{21}$. Convert mixed numbers first.',
      },
      {
        title: 'Divide',
        body: 'Keep the first fraction, multiply by the reciprocal of the second. $\\dfrac{3}{4} \\div \\dfrac{2}{5} = \\dfrac{3}{4} \\times \\dfrac{5}{2} = \\dfrac{15}{8}$.',
      },
      {
        title: 'Fraction of an amount',
        body: 'Multiply by the numerator, divide by the denominator (either order). $\\dfrac{3}{8}$ of $56 = 56 \\div 8 \\times 3 = 21$.',
      },
    ],
    examples: [
      {
        title: 'Simplifying and comparing',
        problem: 'Write $\\dfrac{42}{56}$ in simplest form, then decide which is larger: $\\dfrac{5}{8}$ or $\\dfrac{7}{12}$.',
        steps: [
          'HCF of 42 and 56 is 14, so $\\dfrac{42}{56} = \\dfrac{3}{4}$.',
          'Common denominator of 8 and 12 is 24: $\\dfrac{5}{8} = \\dfrac{15}{24}$ and $\\dfrac{7}{12} = \\dfrac{14}{24}$.',
          '$\\dfrac{15}{24} > \\dfrac{14}{24}$, so $\\dfrac{5}{8}$ is larger.',
        ],
        commonMistake: 'Cancelling 4 from 42 only, or comparing 5 with 7 and 8 with 12 separately.',
      },
      {
        title: 'Adding mixed numbers',
        problem: 'Work out $1\\dfrac{2}{3} + 2\\dfrac{1}{4}$.',
        steps: [
          'Convert: $1\\dfrac{2}{3} = \\dfrac{5}{3}$ and $2\\dfrac{1}{4} = \\dfrac{9}{4}$.',
          'Common denominator 12: $\\dfrac{20}{12} + \\dfrac{27}{12} = \\dfrac{47}{12}$.',
          '$\\dfrac{47}{12} = 3\\dfrac{11}{12}$.',
        ],
        commonMistake: 'Adding the whole numbers and the fractions separately without a common denominator, e.g. writing $3\\dfrac{3}{7}$.',
      },
      {
        title: 'Multiplying and dividing',
        problem: 'Calculate $\\dfrac{5}{6} \\div \\dfrac{2}{3}$ and $\\dfrac{3}{4} \\times \\dfrac{8}{9}$.',
        steps: [
          '$\\dfrac{5}{6} \\div \\dfrac{2}{3} = \\dfrac{5}{6} \\times \\dfrac{3}{2} = \\dfrac{15}{12} = \\dfrac{5}{4}$.',
          '$\\dfrac{3}{4} \\times \\dfrac{8}{9} = \\dfrac{24}{36} = \\dfrac{2}{3}$ (or cancel first: $\\dfrac{3}{1} \\times \\dfrac{2}{9} = \\dfrac{6}{9} = \\dfrac{2}{3}$).',
        ],
        commonMistake: 'Dividing 5 by 2 and 6 by 3 instead of using the reciprocal.',
      },
      {
        title: 'Fraction of a quantity',
        problem: 'A roll of ribbon is 72 m long. $\\dfrac{5}{8}$ is used for costumes. How many metres are left?',
        steps: [
          'Used: $72 \\div 8 \\times 5 = 45$ m.',
          'Left: $72 - 45 = 27$ m.',
          'Check: leftover is $\\dfrac{3}{8}$ of 72, and $72 \\div 8 \\times 3 = 27$.',
        ],
        commonMistake: 'Finding $\\dfrac{5}{8}$ of 72 and forgetting to subtract from the original length.',
      },
    ],
    watchOuts: [
      'Do not add or subtract denominators. $1/2 + 1/3$ is not $2/5$.',
      'Convert mixed numbers before multiplying or dividing.',
      'A reciprocal flips numerator and denominator — $2/3$ becomes $3/2$, not $2/3$ again.',
      'Leave answers in simplest form unless the question asks for a mixed number.',
    ],
  },
  practice: [
    numeric({
      id: 'f-p1',
      skill: 'Equivalent fractions',
      prompt: 'Write $\\dfrac{42}{56}$ in its simplest form.',
      marks: 1,
      answer: '3/4',
      placeholder: 'e.g. 3/4',
      solution: ['HCF of 42 and 56 is 14.', '$42 \\div 14 = 3$ and $56 \\div 14 = 4$, so $\\dfrac{3}{4}$.'],
    }),
    mc({
      id: 'f-p2',
      skill: 'Equivalent fractions',
      prompt: 'Which fraction is equivalent to $\\dfrac{3}{5}$?',
      marks: 1,
      choices: ['$\\dfrac{6}{8}$', '$\\dfrac{9}{15}$', '$\\dfrac{12}{25}$', '$\\dfrac{3}{10}$'],
      correctIndex: 1,
      solution: ['Multiply 3 and 5 by 3: $\\dfrac{9}{15}$.', 'The others change only one part, or use the wrong factor.'],
    }),
    numeric({
      id: 'f-p3',
      skill: 'Mixed numbers',
      prompt: 'Write $3\\dfrac{2}{7}$ as an improper fraction.',
      marks: 1,
      answer: '23/7',
      solution: ['$3 \\times 7 + 2 = 23$, so $\\dfrac{23}{7}$.'],
    }),
    numeric({
      id: 'f-p4',
      skill: 'Mixed numbers',
      prompt: 'Write $\\dfrac{29}{6}$ as a mixed number.',
      marks: 1,
      answer: '4 5/6',
      accepted: ['29/6', '4 5/6'],
      placeholder: 'e.g. 4 5/6',
      solution: ['$29 \\div 6 = 4$ remainder 5, so $4\\dfrac{5}{6}$.'],
    }),
    numeric({
      id: 'f-p5',
      skill: 'Four operations',
      prompt: 'Work out $\\dfrac{2}{5} + \\dfrac{1}{4}$. Give your answer in simplest form.',
      marks: 2,
      answer: '13/20',
      solution: ['Common denominator 20: $\\dfrac{8}{20} + \\dfrac{5}{20} = \\dfrac{13}{20}$.'],
    }),
    numeric({
      id: 'f-p6',
      skill: 'Four operations',
      prompt: 'Work out $\\dfrac{5}{6} - \\dfrac{1}{3}$.',
      marks: 2,
      answer: '1/2',
      accepted: ['3/6'],
      solution: ['$\\dfrac{1}{3} = \\dfrac{2}{6}$, so $\\dfrac{5}{6} - \\dfrac{2}{6} = \\dfrac{3}{6} = \\dfrac{1}{2}$.'],
    }),
    numeric({
      id: 'f-p7',
      skill: 'Four operations',
      prompt: 'Work out $\\dfrac{3}{4} \\times \\dfrac{8}{9}$. Give the answer in simplest form.',
      marks: 2,
      answer: '2/3',
      solution: ['$\\dfrac{3 \\times 8}{4 \\times 9} = \\dfrac{24}{36} = \\dfrac{2}{3}$.', 'Or cancel 4 and 8, then 3 and 9.'],
    }),
    numeric({
      id: 'f-p8',
      skill: 'Four operations',
      prompt: 'Work out $\\dfrac{5}{6} \\div \\dfrac{2}{3}$.',
      marks: 2,
      answer: '5/4',
      accepted: ['1 1/4', '1.25'],
      solution: ['$\\dfrac{5}{6} \\times \\dfrac{3}{2} = \\dfrac{15}{12} = \\dfrac{5}{4}$.'],
    }),
    numeric({
      id: 'f-p9',
      skill: 'Fractions of amounts',
      prompt: 'Work out $\\dfrac{3}{8}$ of 64.',
      marks: 1,
      answer: '24',
      solution: ['$64 \\div 8 = 8$, then $8 \\times 3 = 24$.'],
    }),
    numeric({
      id: 'f-p10',
      skill: 'Fractions of amounts',
      prompt: 'A tank holds 90 litres. $\\dfrac{2}{5}$ is used. How many litres remain?',
      marks: 2,
      answer: '54',
      solution: ['Used: $90 \\div 5 \\times 2 = 36$ litres.', 'Remaining: $90 - 36 = 54$ litres.'],
    }),
    numeric({
      id: 'f-p11',
      skill: 'Mixed numbers',
      prompt: 'Work out $1\\dfrac{2}{3} + 2\\dfrac{1}{4}$. Give your answer as a mixed number.',
      marks: 3,
      answer: '3 11/12',
      accepted: ['47/12'],
      placeholder: 'e.g. 3 11/12',
      solution: [
        '$\\dfrac{5}{3} + \\dfrac{9}{4} = \\dfrac{20}{12} + \\dfrac{27}{12} = \\dfrac{47}{12}$.',
        '$\\dfrac{47}{12} = 3\\dfrac{11}{12}$.',
      ],
    }),
    mc({
      id: 'f-p12',
      skill: 'Equivalent fractions',
      prompt: 'Which statement is true?',
      marks: 1,
      choices: [
        '$\\dfrac{5}{8} < \\dfrac{7}{12}$',
        '$\\dfrac{5}{8} = \\dfrac{7}{12}$',
        '$\\dfrac{5}{8} > \\dfrac{7}{12}$',
      ],
      correctIndex: 2,
      solution: [
        '$\\dfrac{5}{8} = \\dfrac{15}{24}$ and $\\dfrac{7}{12} = \\dfrac{14}{24}$.',
        'So $\\dfrac{5}{8}$ is larger.',
      ],
    }),
    numeric({
      id: 'f-p13',
      skill: 'Four operations',
      prompt: 'A cake is cut into 12 equal slices. Priya eats $\\dfrac{1}{4}$ of the cake and Omar eats 3 slices. What fraction of the cake is left? Give your answer in simplest form.',
      marks: 2,
      answer: '1/2',
      accepted: ['6/12'],
      solution: [
        'Priya eats $\\dfrac{1}{4} = \\dfrac{3}{12}$. Omar eats 3 slices $= \\dfrac{3}{12}$.',
        'Eaten: $\\dfrac{6}{12}$. Left: $\\dfrac{6}{12} = \\dfrac{1}{2}$.',
      ],
    }),
    numeric({
      id: 'f-p14',
      skill: 'Four operations',
      tier: 'H',
      prompt: 'Work out $\\dfrac{2}{3} \\div \\dfrac{4}{5} \\times \\dfrac{3}{8}$. Give your answer in simplest form.',
      marks: 3,
      answer: '5/16',
      solution: [
        '$\\dfrac{2}{3} \\times \\dfrac{5}{4} \\times \\dfrac{3}{8} = \\dfrac{2 \\times 5 \\times 3}{3 \\times 4 \\times 8}$.',
        'Cancel a 3: $\\dfrac{2 \\times 5}{4 \\times 8} = \\dfrac{10}{32} = \\dfrac{5}{16}$.',
      ],
    }),
    multi({
      id: 'f-p15',
      skill: 'Fractions of amounts',
      prompt: 'A school trip costs £84. Students pay $\\dfrac{5}{7}$ of the cost. The rest is paid by a grant.',
      parts: [
        {
          id: 'f-p15a',
          label: 'a',
          prompt: 'How much do the students pay?',
          marks: 1,
          answer: '60',
          solution: ['$84 \\div 7 \\times 5 = 60$.'],
        },
        {
          id: 'f-p15b',
          label: 'b',
          prompt: 'How much is the grant?',
          marks: 1,
          answer: '24',
          solution: ['$84 - 60 = 24$, which is $\\dfrac{2}{7}$ of 84.'],
        },
      ],
    }),
    numeric({
      id: 'f-p16',
      skill: 'Four operations',
      tier: 'H',
      prompt: 'Work out $2\\dfrac{1}{5} \\times 1\\dfrac{1}{4}$. Give your answer as a mixed number.',
      marks: 3,
      answer: '2 3/4',
      accepted: ['11/4', '2.75'],
      placeholder: 'e.g. 2 3/4',
      solution: [
        '$\\dfrac{11}{5} \\times \\dfrac{5}{4} = \\dfrac{11}{4} = 2\\dfrac{3}{4}$.',
      ],
    }),
  ],
  test: {
    durationMinutes: 20,
    questions: [
      numeric({
        id: 'f-t1',
        skill: 'Equivalent fractions',
        prompt: 'Simplify $\\dfrac{36}{60}$.',
        marks: 1,
        answer: '3/5',
        solution: ['HCF is 12: $\\dfrac{36}{60} = \\dfrac{3}{5}$.'],
      }),
      numeric({
        id: 'f-t2',
        skill: 'Mixed numbers',
        prompt: 'Write $4\\dfrac{3}{5}$ as an improper fraction.',
        marks: 1,
        answer: '23/5',
        solution: ['$4 \\times 5 + 3 = 23$, so $\\dfrac{23}{5}$.'],
      }),
      numeric({
        id: 'f-t3',
        skill: 'Four operations',
        prompt: 'Work out $\\dfrac{3}{8} + \\dfrac{1}{6}$.',
        marks: 2,
        answer: '13/24',
        solution: ['Common denominator 24: $\\dfrac{9}{24} + \\dfrac{4}{24} = \\dfrac{13}{24}$.'],
      }),
      numeric({
        id: 'f-t4',
        skill: 'Four operations',
        prompt: 'Work out $\\dfrac{7}{10} - \\dfrac{1}{4}$.',
        marks: 2,
        answer: '9/20',
        solution: ['$\\dfrac{14}{20} - \\dfrac{5}{20} = \\dfrac{9}{20}$.'],
      }),
      numeric({
        id: 'f-t5',
        skill: 'Four operations',
        prompt: 'Work out $\\dfrac{5}{9} \\times \\dfrac{3}{10}$.',
        marks: 2,
        answer: '1/6',
        solution: ['$\\dfrac{15}{90} = \\dfrac{1}{6}$.'],
      }),
      numeric({
        id: 'f-t6',
        skill: 'Four operations',
        prompt: 'Work out $\\dfrac{7}{8} \\div \\dfrac{1}{4}$.',
        marks: 2,
        answer: '7/2',
        accepted: ['3 1/2', '3.5'],
        solution: ['$\\dfrac{7}{8} \\times 4 = \\dfrac{28}{8} = \\dfrac{7}{2}$.'],
      }),
      numeric({
        id: 'f-t7',
        skill: 'Fractions of amounts',
        prompt: 'Find $\\dfrac{5}{12}$ of 96.',
        marks: 2,
        answer: '40',
        solution: ['$96 \\div 12 = 8$, $8 \\times 5 = 40$.'],
      }),
      numeric({
        id: 'f-t8',
        skill: 'Mixed numbers',
        prompt: 'Work out $3\\dfrac{1}{6} - 1\\dfrac{2}{3}$. Give your answer as a mixed number or improper fraction in simplest form.',
        marks: 3,
        answer: '3/2',
        accepted: ['1 1/2', '1.5'],
        solution: [
          '$\\dfrac{19}{6} - \\dfrac{5}{3} = \\dfrac{19}{6} - \\dfrac{10}{6} = \\dfrac{9}{6} = \\dfrac{3}{2}$.',
        ],
      }),
      numeric({
        id: 'f-t9',
        skill: 'Four operations',
        tier: 'H',
        prompt: 'Work out $\\left(\\dfrac{5}{6} + \\dfrac{1}{3}\\right) \\div \\dfrac{7}{9}$.',
        marks: 3,
        answer: '3/2',
        accepted: ['1 1/2', '1.5'],
        solution: [
          '$\\dfrac{5}{6} + \\dfrac{2}{6} = \\dfrac{7}{6}$.',
          '$\\dfrac{7}{6} \\times \\dfrac{9}{7} = \\dfrac{9}{6} = \\dfrac{3}{2}$.',
        ],
      }),
    ],
  },
}
