import { getChapter } from '../catalog'
import { mc, multi, numeric } from '../make'
import type { ChapterContent } from '../../lib/types'

const meta = getChapter(5)!

export const chapter05: ChapterContent = {
  meta,
  theory: {
    goal: 'Find a percentage of an amount, increase and decrease using multipliers, and reverse a percentage change to recover the original value.',
    youNeedFirst: [
      'Fractions and decimals as parts of 1',
      'Multiplying and dividing by 10, 100 and 1000',
      'The idea of a multiplier such as $1.2$ or $0.85$',
    ],
    keyFacts: [
      {
        title: 'Percent means out of 100',
        body: '$35\\% = \\dfrac{35}{100} = 0.35$. To find $35\\%$ of 80, calculate $0.35 \\times 80 = 28$.',
      },
      {
        title: 'Simple percentages first',
        body: '$10\\%$ is $\\div 10$, $5\\%$ is half of $10\\%$, $1\\%$ is $\\div 100$. Build other percentages from these.',
      },
      {
        title: 'Increase and decrease multipliers',
        body: 'A $12\\%$ increase uses $\\times 1.12$. A $12\\%$ decrease uses $\\times 0.88$. New value $= \\text{original} \\times \\text{multiplier}$.',
      },
      {
        title: 'Express as a percentage',
        body: '$\\dfrac{\\text{part}}{\\text{whole}} \\times 100$. 18 out of 24 is $\\dfrac{18}{24} \\times 100 = 75\\%$.',
      },
      {
        title: 'Reverse percentages',
        body: 'If a price after a $20\\%$ increase is £84, that £84 is $120\\%$ of the original. Original $= 84 \\div 1.2 = 70$. Do **not** subtract $20\\%$ of 84.',
      },
      {
        title: 'Repeated change (Higher)',
        body: 'Apply the multiplier once per period. Two years at $4\\%$ compound growth: $\\times 1.04^2$, not $\\times 1.08$.',
      },
    ],
    examples: [
      {
        title: 'Percentage of an amount',
        problem: 'A jumper costs £45. In a sale it is reduced by $30\\%$. What is the sale price?',
        steps: [
          'Multiplier for a $30\\%$ decrease is $0.70$.',
          'Sale price $= 45 \\times 0.70 = £31.50$.',
          'Check: $10\\%$ of 45 is £4.50, so $30\\%$ is £13.50, and $45 - 13.50 = 31.50$.',
        ],
        commonMistake: 'Finding $30\\%$ and forgetting to subtract, or using $1.30$ (an increase).',
      },
      {
        title: 'Reverse percentage',
        problem: 'After a $15\\%$ pay rise, Jordan earns £2070 per month. What was the monthly pay before the rise?',
        steps: [
          '£2070 is $115\\%$ of the original, so the multiplier is $1.15$.',
          'Original $= 2070 \\div 1.15 = 1800$.',
          'Check: $15\\%$ of 1800 is 270, and $1800 + 270 = 2070$.',
        ],
        commonMistake: 'Taking $15\\%$ of 2070 and subtracting. That answers a different question.',
      },
      {
        title: 'Expressing a change',
        problem: 'A club had 80 members. It now has 92. Work out the percentage increase.',
        steps: [
          'Increase $= 92 - 80 = 12$.',
          'Percentage increase $= \\dfrac{12}{80} \\times 100 = 15\\%$.',
        ],
        commonMistake: 'Dividing 12 by 92 (the new amount) instead of by the original 80.',
      },
      {
        title: 'Compound change (Higher)',
        problem: '£2500 is invested at $4\\%$ compound interest for 2 years. How much interest is earned?',
        steps: [
          'After 2 years: $2500 \\times 1.04^2 = 2500 \\times 1.0816 = 2704$.',
          'Interest $= 2704 - 2500 = £204$.',
        ],
        commonMistake: 'Doing $2 \\times 4\\% = 8\\%$ of 2500, which is simple interest (£200), not compound.',
      },
    ],
    watchOuts: [
      'Reverse percentages: divide by the multiplier. Never subtract the percentage of the new amount.',
      'Decide increase vs decrease before you pick $1.p$ or $1-p$.',
      'Percentage change is always compared with the **original** value.',
      'Two 10% increases are $\\times 1.1^2 = 1.21$, a 21% increase, not 20%.',
    ],
  },
  practice: [
    numeric({
      id: 'p-p1',
      skill: 'Percentage of an amount',
      prompt: 'Work out $15\\%$ of 240.',
      marks: 1,
      answer: '36',
      solution: ['$10\\% = 24$, $5\\% = 12$, so $15\\% = 36$.', 'Or $0.15 \\times 240 = 36$.'],
    }),
    numeric({
      id: 'p-p2',
      skill: 'Percentage of an amount',
      prompt: 'A bottle contains 750 ml. $8\\%$ is lost to spillage. How many millilitres are lost?',
      marks: 1,
      answer: '60',
      solution: ['$1\\% = 7.5$ ml, so $8\\% = 60$ ml.'],
    }),
    numeric({
      id: 'p-p3',
      skill: 'Increase and decrease',
      prompt: 'Increase 80 by $12\\%$.',
      marks: 2,
      answer: '89.6',
      accepted: ['89.60'],
      solution: ['Multiplier $1.12$. $80 \\times 1.12 = 89.6$.'],
    }),
    numeric({
      id: 'p-p4',
      skill: 'Increase and decrease',
      prompt: 'A coat costs £65. It is reduced by $20\\%$ in a sale. What is the sale price in pounds?',
      marks: 2,
      answer: '52',
      solution: ['$65 \\times 0.8 = 52$.'],
    }),
    numeric({
      id: 'p-p5',
      skill: 'Increase and decrease',
      prompt: 'Last year a train fare was £40. This year it is £46. What is the percentage increase?',
      marks: 2,
      answer: '15',
      accepted: ['15%'],
      placeholder: 'e.g. 15',
      solution: ['Increase $= 6$. $\\dfrac{6}{40} \\times 100 = 15\\%$.'],
    }),
    numeric({
      id: 'p-p6',
      skill: 'Percentage of an amount',
      prompt: 'Write $\\dfrac{11}{20}$ as a percentage.',
      marks: 1,
      answer: '55',
      accepted: ['55%'],
      solution: ['$\\dfrac{11}{20} = 0.55 = 55\\%$.'],
    }),
    numeric({
      id: 'p-p7',
      skill: 'Reverse percentages',
      prompt: 'After a $25\\%$ increase, a ticket costs £40. What was the original price in pounds?',
      marks: 2,
      answer: '32',
      solution: ['£40 is $125\\%$ of the original. $40 \\div 1.25 = 32$.'],
    }),
    numeric({
      id: 'p-p8',
      skill: 'Reverse percentages',
      prompt: 'A laptop is in a $15\\%$ off sale and now costs £340. What was the pre-sale price in pounds?',
      marks: 2,
      answer: '400',
      solution: ['£340 is $85\\%$ of the original. $340 \\div 0.85 = 400$.'],
    }),
    mc({
      id: 'p-p9',
      skill: 'Multipliers',
      prompt: 'Which multiplier gives a $7\\%$ decrease?',
      marks: 1,
      choices: ['$1.07$', '$0.07$', '$0.93$', '$1.70$'],
      correctIndex: 2,
      solution: ['A decrease of $7\\%$ leaves $93\\%$, so multiply by $0.93$.'],
    }),
    numeric({
      id: 'p-p10',
      skill: 'Increase and decrease',
      prompt: 'VAT at $20\\%$ is added to a net price of £85. What is the total price in pounds?',
      marks: 2,
      answer: '102',
      solution: ['$85 \\times 1.2 = 102$.'],
    }),
    multi({
      id: 'p-p11',
      skill: 'Reverse percentages',
      prompt: 'A shop adds $20\\%$ VAT at the till. A customer pays £54 including VAT.',
      parts: [
        {
          id: 'p-p11a',
          label: 'a',
          prompt: 'What was the price before VAT, in pounds?',
          marks: 2,
          answer: '45',
          solution: ['$54 \\div 1.2 = 45$.'],
        },
        {
          id: 'p-p11b',
          label: 'b',
          prompt: 'How much VAT was paid, in pounds?',
          marks: 1,
          answer: '9',
          solution: ['$54 - 45 = 9$.'],
        },
      ],
    }),
    numeric({
      id: 'p-p12',
      skill: 'Percentage of an amount',
      prompt: 'In a year group of 180 students, $35\\%$ walk to school, $45\\%$ come by bus and the rest cycle. How many cycle?',
      marks: 2,
      answer: '36',
      solution: ['Walk or bus: $80\\%$. Cycle: $20\\%$ of 180 $= 36$.'],
    }),
    numeric({
      id: 'p-p13',
      skill: 'Multipliers',
      tier: 'H',
      prompt: '£1600 is invested at $5\\%$ compound interest for 2 years. What is the value after 2 years, in pounds?',
      marks: 3,
      answer: '1764',
      solution: ['$1600 \\times 1.05^2 = 1600 \\times 1.1025 = 1764$.'],
    }),
    numeric({
      id: 'p-p14',
      skill: 'Reverse percentages',
      tier: 'H',
      prompt: 'A population falls by $8\\%$ to 4140. What was the population before the fall?',
      marks: 3,
      answer: '4500',
      solution: ['4140 is $92\\%$ of the original. $4140 \\div 0.92 = 4500$.'],
    }),
    numeric({
      id: 'p-p15',
      skill: 'Increase and decrease',
      prompt: 'A shirt is reduced from £32 to £24. Work out the percentage decrease.',
      marks: 2,
      answer: '25',
      accepted: ['25%'],
      solution: ['Decrease $= 8$. $\\dfrac{8}{32} \\times 100 = 25\\%$.'],
    }),
    numeric({
      id: 'p-p16',
      skill: 'Multipliers',
      tier: 'H',
      prompt: 'A price is increased by $10\\%$ and then decreased by $10\\%$. If the original price was £200, what is the final price in pounds?',
      marks: 2,
      answer: '198',
      solution: [
        'After increase: $200 \\times 1.1 = 220$.',
        'After decrease: $220 \\times 0.9 = 198$.',
        'The changes do not cancel. Combined multiplier $1.1 \\times 0.9 = 0.99$.',
      ],
    }),
  ],
  test: {
    durationMinutes: 20,
    questions: [
      numeric({
        id: 'p-t1',
        skill: 'Percentage of an amount',
        prompt: 'Work out $17\\%$ of 300.',
        marks: 1,
        answer: '51',
        solution: ['$10\\% = 30$, $5\\% = 15$, $2\\% = 6$, total $51$.'],
      }),
      numeric({
        id: 'p-t2',
        skill: 'Increase and decrease',
        prompt: 'Decrease 90 by $15\\%$.',
        marks: 2,
        answer: '76.5',
        solution: ['$90 \\times 0.85 = 76.5$.'],
      }),
      numeric({
        id: 'p-t3',
        skill: 'Increase and decrease',
        prompt: 'A shop buys a kettle for £18 and sells it for £24. What is the percentage profit?',
        marks: 2,
        answer: '33.333',
        accepted: ['33.3', '33.33', '33.\\dot{3}', '100/3', '33 1/3'],
        tolerance: 0.05,
        solution: ['Profit $= 6$. $\\dfrac{6}{18} \\times 100 = 33.\\dot{3}\\%$.'],
      }),
      numeric({
        id: 'p-t4',
        skill: 'Reverse percentages',
        prompt: 'After a $10\\%$ increase a bill is £66. What was the bill before the increase?',
        marks: 2,
        answer: '60',
        solution: ['$66 \\div 1.1 = 60$.'],
      }),
      numeric({
        id: 'p-t5',
        skill: 'Reverse percentages',
        prompt: 'In a $20\\%$ off sale a game costs £28. What was the original price?',
        marks: 2,
        answer: '35',
        solution: ['£28 is $80\\%$. $28 \\div 0.8 = 35$.'],
      }),
      numeric({
        id: 'p-t6',
        skill: 'Percentage of an amount',
        prompt: '36 out of 48 students passed a test. What percentage passed?',
        marks: 2,
        answer: '75',
        accepted: ['75%'],
        solution: ['$\\dfrac{36}{48} \\times 100 = 75\\%$.'],
      }),
      numeric({
        id: 'p-t7',
        skill: 'Multipliers',
        prompt: 'A season ticket costs £250. Next year the price rises by $6\\%$. What is the new price in pounds?',
        marks: 2,
        answer: '265',
        solution: ['$250 \\times 1.06 = 265$.'],
      }),
      numeric({
        id: 'p-t7b',
        skill: 'Increase and decrease',
        prompt: 'A jacket costs £40. It is reduced by $25\\%$. What is the sale price in pounds?',
        marks: 2,
        answer: '30',
        solution: ['$40 \\times 0.75 = 30$.'],
      }),
      numeric({
        id: 'p-t8',
        skill: 'Reverse percentages',
        tier: 'H',
        prompt: 'A value increases by $12\\%$ to 1680. Find the original value.',
        marks: 3,
        answer: '1500',
        solution: ['$1680 \\div 1.12 = 1500$.'],
      }),
      numeric({
        id: 'p-t9',
        skill: 'Multipliers',
        tier: 'H',
        prompt: '£2000 is saved at $3\\%$ compound interest for 2 years. How much interest is earned, in pounds?',
        marks: 3,
        answer: '121.8',
        accepted: ['121.80'],
        tolerance: 0.01,
        solution: [
          '$2000 \\times 1.03^2 = 2000 \\times 1.0609 = 2121.80$.',
          'Interest $= 2121.80 - 2000 = 121.80$.',
        ],
      }),
    ],
  },
}
