import { getChapter } from '../catalog'
import { mc, multi, numeric } from '../make'
import type { ChapterContent } from '../../lib/types'

const meta = getChapter(11)!

export const chapter11: ChapterContent = {
  meta,
  theory: {
    goal: 'Solve linear equations by balancing both sides, including equations with brackets, unknowns on both sides, and (on Higher) simple fractional equations.',
    youNeedFirst: [
      'Collecting like terms',
      'Directed-number arithmetic',
      'Expanding a single bracket',
    ],
    keyFacts: [
      {
        title: 'Balance',
        body: 'Whatever you do to one side, do to the other. Inverse operations undo each other: add/subtract, multiply/divide.',
      },
      {
        title: 'One- and two-step',
        body: '$x + 7 = 20$ gives $x = 13$. $3x - 5 = 16$ add 5 then divide by 3: $x = 7$.',
      },
      {
        title: 'Brackets first',
        body: 'Expand, then collect. $2(x + 4) = 18 \\Rightarrow 2x + 8 = 18 \\Rightarrow 2x = 10 \\Rightarrow x = 5$.',
      },
      {
        title: 'Unknowns on both sides',
        body: 'Collect $x$ terms on one side and numbers on the other. $5x - 2 = 3x + 10 \\Rightarrow 2x = 12 \\Rightarrow x = 6$.',
      },
      {
        title: 'Fractional equations (Higher)',
        body: 'Multiply through by the denominator to clear the fraction. $\\dfrac{x}{4} + 3 = 8 \\Rightarrow x + 12 = 32 \\Rightarrow x = 20$.',
      },
      {
        title: 'Check by substituting',
        body: 'Put your answer back into the original equation. If both sides match, the solution is correct.',
      },
    ],
    examples: [
      {
        title: 'Two-step equation',
        problem: 'Solve $4x + 9 = 37$.',
        steps: [
          'Subtract 9 from both sides: $4x = 28$.',
          'Divide by 4: $x = 7$.',
          'Check: $4 \\times 7 + 9 = 28 + 9 = 37$.',
        ],
        commonMistake: 'Dividing 37 by 4 first, then subtracting 9.',
      },
      {
        title: 'Brackets',
        problem: 'Solve $3(2x - 1) = 27$.',
        steps: [
          'Expand: $6x - 3 = 27$.',
          'Add 3: $6x = 30$.',
          'Divide by 6: $x = 5$.',
        ],
        commonMistake: 'Dividing 27 by 3 but forgetting to divide the whole left-hand side, or writing $3 \\times 2x - 1$.',
      },
      {
        title: 'Unknowns on both sides',
        problem: 'Solve $7x - 4 = 3x + 18$.',
        steps: [
          'Subtract $3x$: $4x - 4 = 18$.',
          'Add 4: $4x = 22$.',
          'Divide by 4: $x = 5.5$ or $\\dfrac{11}{2}$.',
        ],
        commonMistake: 'Subtracting $7x$ from $3x$ and flipping the equation without changing the numbers.',
      },
      {
        title: 'Fractions (Higher)',
        problem: 'Solve $\\dfrac{2x - 1}{3} = 5$.',
        steps: [
          'Multiply both sides by 3: $2x - 1 = 15$.',
          'Add 1: $2x = 16$.',
          'Divide by 2: $x = 8$.',
        ],
        commonMistake: 'Multiplying only the $2x$ by 3, or adding 1 before clearing the denominator.',
      },
    ],
    watchOuts: [
      'Apply an operation to **every** term on both sides.',
      'When expanding $-(x - 4)$, the 4 becomes $+4$.',
      'If you move a term across the equals sign, change its sign.',
      'A negative solution is allowed. Check it by substitution.',
    ],
  },
  practice: [
    numeric({
      id: 'e-p1',
      skill: 'One- and two-step',
      prompt: 'Solve $x + 17 = 41$.',
      marks: 1,
      answer: '24',
      solution: ['Subtract 17: $x = 24$.'],
    }),
    numeric({
      id: 'e-p2',
      skill: 'One- and two-step',
      prompt: 'Solve $5x = 45$.',
      marks: 1,
      answer: '9',
      solution: ['Divide by 5: $x = 9$.'],
    }),
    numeric({
      id: 'e-p3',
      skill: 'One- and two-step',
      prompt: 'Solve $3x - 8 = 19$.',
      marks: 2,
      answer: '9',
      solution: ['Add 8: $3x = 27$. Divide by 3: $x = 9$.'],
    }),
    numeric({
      id: 'e-p4',
      skill: 'One- and two-step',
      prompt: 'Solve $\\dfrac{x}{6} = 7$.',
      marks: 1,
      answer: '42',
      solution: ['Multiply by 6: $x = 42$.'],
    }),
    numeric({
      id: 'e-p5',
      skill: 'Brackets',
      prompt: 'Solve $2(x + 5) = 24$.',
      marks: 2,
      answer: '7',
      solution: ['$2x + 10 = 24$, so $2x = 14$ and $x = 7$.'],
    }),
    numeric({
      id: 'e-p6',
      skill: 'Brackets',
      prompt: 'Solve $4(2x - 3) = 20$.',
      marks: 2,
      answer: '4',
      solution: ['$8x - 12 = 20$, $8x = 32$, $x = 4$.'],
    }),
    numeric({
      id: 'e-p7',
      skill: 'Unknowns on both sides',
      prompt: 'Solve $5x + 2 = 3x + 16$.',
      marks: 2,
      answer: '7',
      solution: ['Subtract $3x$: $2x + 2 = 16$. Subtract 2: $2x = 14$. $x = 7$.'],
    }),
    numeric({
      id: 'e-p8',
      skill: 'Unknowns on both sides',
      prompt: 'Solve $8x - 9 = 4x + 7$.',
      marks: 2,
      answer: '4',
      solution: ['$4x - 9 = 7$, $4x = 16$, $x = 4$.'],
    }),
    numeric({
      id: 'e-p9',
      skill: 'One- and two-step',
      prompt: 'Solve $7 - 2x = 1$.',
      marks: 2,
      answer: '3',
      solution: ['Subtract 7: $-2x = -6$. Divide by $-2$: $x = 3$.'],
    }),
    mc({
      id: 'e-p10',
      skill: 'Brackets',
      prompt: 'Which equation is equivalent to $3(x - 4) = 15$?',
      marks: 1,
      choices: ['$3x - 4 = 15$', '$3x - 12 = 15$', '$3x - 12 = 5$', '$x - 4 = 15$'],
      correctIndex: 1,
      solution: ['Expand: $3x - 12 = 15$.'],
    }),
    numeric({
      id: 'e-p11',
      skill: 'Unknowns on both sides',
      prompt: 'Solve $2x + 11 = 5x - 4$.',
      marks: 2,
      answer: '5',
      solution: ['Add 4: $2x + 15 = 5x$. Subtract $2x$: $15 = 3x$. $x = 5$.'],
    }),
    numeric({
      id: 'e-p12',
      skill: 'Brackets',
      prompt: 'Solve $5(x - 2) = 3(x + 4)$.',
      marks: 3,
      answer: '11',
      solution: ['$5x - 10 = 3x + 12$. Subtract $3x$: $2x - 10 = 12$. Add 10: $2x = 22$. $x = 11$.'],
    }),
    numeric({
      id: 'e-p13',
      skill: 'Fractional equations',
      tier: 'H',
      prompt: 'Solve $\\dfrac{x}{4} + 5 = 11$.',
      marks: 2,
      answer: '24',
      solution: ['Subtract 5: $\\dfrac{x}{4} = 6$. Multiply by 4: $x = 24$.'],
    }),
    numeric({
      id: 'e-p14',
      skill: 'Fractional equations',
      tier: 'H',
      prompt: 'Solve $\\dfrac{2x - 3}{5} = 3$.',
      marks: 3,
      answer: '9',
      solution: ['Multiply by 5: $2x - 3 = 15$. Add 3: $2x = 18$. $x = 9$.'],
    }),
    multi({
      id: 'e-p15',
      skill: 'One- and two-step',
      prompt: 'A rectangle has width $x$ cm and length $(x + 6)$ cm. The perimeter is 44 cm.',
      parts: [
        {
          id: 'e-p15a',
          label: 'a',
          prompt: 'Write an equation for $x$. Use the form $ax + b = c$ or similar. Then find $x$. What is $x$?',
          marks: 2,
          answer: '8',
          solution: ['$2x + 2(x + 6) = 44 \\Rightarrow 4x + 12 = 44 \\Rightarrow 4x = 32 \\Rightarrow x = 8$.'],
        },
        {
          id: 'e-p15b',
          label: 'b',
          prompt: 'What is the length, in centimetres?',
          marks: 1,
          answer: '14',
          solution: ['Length $= 8 + 6 = 14$.'],
        },
      ],
    }),
    numeric({
      id: 'e-p16',
      skill: 'Unknowns on both sides',
      tier: 'H',
      prompt: 'Solve $3(2x + 1) - 4 = 2(x - 5) + 21$.',
      marks: 3,
      answer: '3',
      solution: [
        'Left: $6x + 3 - 4 = 6x - 1$. Right: $2x - 10 + 21 = 2x + 11$.',
        '$6x - 1 = 2x + 11 \\Rightarrow 4x = 12 \\Rightarrow x = 3$.',
      ],
    }),
  ],
  test: {
    durationMinutes: 20,
    questions: [
      numeric({
        id: 'e-t1',
        skill: 'One- and two-step',
        prompt: 'Solve $x - 13 = 9$.',
        marks: 1,
        answer: '22',
        solution: ['Add 13: $x = 22$.'],
      }),
      numeric({
        id: 'e-t2',
        skill: 'One- and two-step',
        prompt: 'Solve $6x + 5 = 29$.',
        marks: 2,
        answer: '4',
        solution: ['$6x = 24$, $x = 4$.'],
      }),
      numeric({
        id: 'e-t3',
        skill: 'Brackets',
        prompt: 'Solve $3(x + 7) = 36$.',
        marks: 2,
        answer: '5',
        solution: ['$3x + 21 = 36$, $3x = 15$, $x = 5$.'],
      }),
      numeric({
        id: 'e-t4',
        skill: 'Unknowns on both sides',
        prompt: 'Solve $9x - 6 = 5x + 14$.',
        marks: 2,
        answer: '5',
        solution: ['$4x - 6 = 14$, $4x = 20$, $x = 5$.'],
      }),
      numeric({
        id: 'e-t5',
        skill: 'One- and two-step',
        prompt: 'Solve $11 - 3x = 2$.',
        marks: 2,
        answer: '3',
        solution: ['$-3x = -9$, $x = 3$.'],
      }),
      numeric({
        id: 'e-t6',
        skill: 'Brackets',
        prompt: 'Solve $2(3x - 4) = 5x + 3$.',
        marks: 3,
        answer: '11',
        solution: ['$6x - 8 = 5x + 3$, $x = 11$.'],
      }),
      numeric({
        id: 'e-t7',
        skill: 'Unknowns on both sides',
        prompt: 'Solve $4(x + 2) = 2(x + 11)$.',
        marks: 3,
        answer: '7',
        solution: ['$4x + 8 = 2x + 22$, $2x = 14$, $x = 7$.'],
      }),
      numeric({
        id: 'e-t8',
        skill: 'Fractional equations',
        tier: 'H',
        prompt: 'Solve $\\dfrac{x + 4}{3} = 6$.',
        marks: 2,
        answer: '14',
        solution: ['$x + 4 = 18$, $x = 14$.'],
      }),
      numeric({
        id: 'e-t9',
        skill: 'Fractional equations',
        tier: 'H',
        prompt: 'Solve $\\dfrac{3x}{2} - 5 = 7$.',
        marks: 3,
        answer: '8',
        solution: ['$\\dfrac{3x}{2} = 12$, $3x = 24$, $x = 8$.'],
      }),
    ],
  },
}
