import { getChapter } from '../catalog'
import { mc, multi, numeric } from '../make'
import type { ChapterContent } from '../../lib/types'

const meta = getChapter(17)!

export const chapter17: ChapterContent = {
  meta,
  theory: {
    goal: 'Simplify ratios, share an amount in a given ratio, find one part or the total, and (on Higher) combine two-step ratios.',
    youNeedFirst: [
      'Highest common factor',
      'Equivalent fractions',
      'Unitary method (finding 1 part)',
    ],
    keyFacts: [
      {
        title: 'Simplifying a ratio',
        body: 'Divide every part by the HCF. $18 : 24 = 3 : 4$. Units must match before you simplify ($80\\text{ cm} : 2\\text{ m} = 80 : 200 = 2 : 5$).',
      },
      {
        title: 'Sharing an amount',
        body: 'Add the parts, divide the total by that sum, then multiply by each part. Share £70 in the ratio $3 : 4$: 7 parts $= £10$ each, so £30 and £40.',
      },
      {
        title: 'Given one part',
        body: 'If the $3$ in $3 : 5$ is 21, one part is $21 \\div 3 = 7$, so the other is $5 \\times 7 = 35$ and the total is $8 \\times 7 = 56$.',
      },
      {
        title: 'Writing $1 : n$',
        body: 'Divide both sides by the first number. $4 : 10 = 1 : 2.5$. Useful for maps and recipes.',
      },
      {
        title: 'Difference of parts',
        body: 'If A has 12 more than B in the ratio $5 : 3$, the extra 2 parts are 12, so one part is 6. A has 30, B has 18.',
      },
      {
        title: 'Combining ratios (Higher)',
        body: 'To combine $A:B = 2:3$ and $B:C = 4:5$, make the $B$ numbers equal: $8:12$ and $12:15$, so $A:B:C = 8:12:15$.',
      },
    ],
    examples: [
      {
        title: 'Sharing a total',
        problem: 'Share 96 sweets in the ratio $5 : 3$.',
        steps: [
          'Parts: $5 + 3 = 8$. One part $= 96 \\div 8 = 12$.',
          'First share: $5 \\times 12 = 60$. Second: $3 \\times 12 = 36$.',
          'Check: $60 + 36 = 96$.',
        ],
        commonMistake: 'Dividing 96 by 5 and by 3 separately, which does not add up to 96.',
      },
      {
        title: 'Finding a missing part',
        problem: 'Paint is mixed red to white in the ratio $2 : 7$. A tin uses 14 litres of white. How much red is used?',
        steps: [
          'White is 7 parts $= 14$ litres, so one part $= 2$ litres.',
          'Red is 2 parts $= 4$ litres.',
        ],
        commonMistake: 'Treating 14 as the total and sharing it $2 : 7$.',
      },
      {
        title: 'Using a difference',
        problem: 'Two siblings share pocket money in the ratio $4 : 3$. The older sibling receives £12 more. How much does each receive?',
        steps: [
          'The difference is 1 part $= £12$.',
          'Older: $4 \\times 12 = £48$. Younger: $3 \\times 12 = £36$.',
        ],
        commonMistake: 'Sharing £12 in the ratio $4 : 3$ instead of treating £12 as the extra part.',
      },
      {
        title: 'Combining ratios (Higher)',
        problem: 'In a workshop, metal to wood is $3 : 5$ and wood to plastic is $2 : 1$. Find metal : wood : plastic.',
        steps: [
          'Metal : wood $= 3 : 5$. Wood : plastic $= 2 : 1$.',
          'Make wood equal: LCM of 5 and 2 is 10.',
          'Metal : wood $= 6 : 10$. Wood : plastic $= 10 : 5$.',
          'So metal : wood : plastic $= 6 : 10 : 5$.',
        ],
        commonMistake: 'Writing $3 : 5 : 1$ without matching the wood parts.',
      },
    ],
    watchOuts: [
      'Convert to the same units before simplifying.',
      'Decide whether the given number is a **part**, a **total**, or a **difference**.',
      'The order in a ratio matters: $2 : 5$ is not $5 : 2$.',
      'When combining ratios, only the linking quantity must be made equal.',
    ],
  },
  practice: [
    numeric({
      id: 'r-p1',
      skill: 'Simplifying ratios',
      prompt: 'Simplify $18 : 24$. Write your answer as $a:b$.',
      marks: 1,
      answer: '3:4',
      placeholder: 'e.g. 3:4',
      solution: ['HCF is 6. $18 \\div 6 = 3$ and $24 \\div 6 = 4$.'],
    }),
    numeric({
      id: 'r-p2',
      skill: 'Simplifying ratios',
      prompt: 'Simplify $80\\text{ cm} : 2\\text{ m}$. Write $a:b$ in centimetres.',
      marks: 2,
      answer: '2:5',
      solution: ['$2\\text{ m} = 200\\text{ cm}$. $80 : 200 = 2 : 5$.'],
    }),
    numeric({
      id: 'r-p3',
      skill: 'Sharing in a ratio',
      prompt: 'Share £70 in the ratio $3 : 4$. What is the smaller share, in pounds?',
      marks: 2,
      answer: '30',
      solution: ['7 parts $= £10$ each. Smaller share is $3 \\times 10 = 30$.'],
    }),
    numeric({
      id: 'r-p4',
      skill: 'Sharing in a ratio',
      prompt: 'Share 96 in the ratio $5 : 3$. What is the larger share?',
      marks: 2,
      answer: '60',
      solution: ['8 parts $= 12$. Larger: $5 \\times 12 = 60$.'],
    }),
    numeric({
      id: 'r-p5',
      skill: 'Finding a part',
      prompt: 'A ratio is $2 : 7$. The second quantity is 14. What is the first quantity?',
      marks: 2,
      answer: '4',
      solution: ['7 parts $= 14$, so 1 part $= 2$. First quantity $= 4$.'],
    }),
    numeric({
      id: 'r-p6',
      skill: 'Finding a part',
      prompt: 'Cement to sand is $1 : 4$. A mix uses 12 kg of sand. How many kilograms of cement are needed?',
      marks: 1,
      answer: '3',
      solution: ['4 parts $= 12$ kg, so 1 part $= 3$ kg of cement.'],
    }),
    numeric({
      id: 'r-p7',
      skill: 'Sharing in a ratio',
      prompt: 'Three students share 120 counters in the ratio $2 : 3 : 5$. How many does the student with the largest share get?',
      marks: 2,
      answer: '60',
      solution: ['$2 + 3 + 5 = 10$ parts. One part $= 12$. Largest $= 5 \\times 12 = 60$.'],
    }),
    mc({
      id: 'r-p8',
      skill: 'Simplifying ratios',
      prompt: 'Which ratio is equivalent to $6 : 15$?',
      marks: 1,
      choices: ['$2 : 3$', '$2 : 5$', '$3 : 5$', '$4 : 9$'],
      correctIndex: 1,
      solution: ['Divide by 3: $2 : 5$.'],
    }),
    numeric({
      id: 'r-p9',
      skill: 'Finding a part',
      prompt: 'Two people share money in the ratio $5 : 3$. The first person receives £12 more than the second. How much does the first person receive, in pounds?',
      marks: 3,
      answer: '30',
      solution: ['Difference is 2 parts $= £12$, so 1 part $= £6$. First person: $5 \\times 6 = 30$.'],
    }),
    numeric({
      id: 'r-p10',
      skill: 'Sharing in a ratio',
      prompt: 'A drink is squash to water in the ratio $2 : 9$. How much squash is needed to make 440 ml of drink? Give your answer in millilitres.',
      marks: 2,
      answer: '80',
      solution: ['11 parts $= 440$ ml. One part $= 40$ ml. Squash $= 80$ ml.'],
    }),
    multi({
      id: 'r-p11',
      skill: 'Finding a part',
      prompt: 'A recipe for 8 people uses flour and butter in the ratio $5 : 2$. The recipe uses 200 g of flour.',
      parts: [
        {
          id: 'r-p11a',
          label: 'a',
          prompt: 'How many grams of butter are used?',
          marks: 2,
          answer: '80',
          solution: ['5 parts $= 200$ g, so 1 part $= 40$ g. Butter $= 80$ g.'],
        },
        {
          id: 'r-p11b',
          label: 'b',
          prompt: 'How many grams of flour are needed for 12 people?',
          marks: 2,
          answer: '300',
          solution: ['8 people use 200 g, so 1 person uses 25 g. 12 people: $300$ g.'],
        },
      ],
    }),
    numeric({
      id: 'r-p12',
      skill: 'Simplifying ratios',
      prompt: 'Write $4 : 10$ in the form $1 : n$.',
      marks: 1,
      answer: '1:2.5',
      accepted: ['1:5/2', '1:2 1/2'],
      placeholder: 'e.g. 1:2.5',
      solution: ['Divide both parts by 4: $1 : 2.5$.'],
    }),
    numeric({
      id: 'r-p13',
      skill: 'Combining ratios',
      tier: 'H',
      prompt: '$A : B = 2 : 3$ and $B : C = 4 : 5$. Find $A : C$ in simplest form. Write $a:b$.',
      marks: 3,
      answer: '8:15',
      solution: [
        'Make $B$ equal. LCM of 3 and 4 is 12.',
        '$A : B = 8 : 12$ and $B : C = 12 : 15$.',
        '$A : C = 8 : 15$.',
      ],
    }),
    numeric({
      id: 'r-p14',
      skill: 'Combining ratios',
      tier: 'H',
      prompt: 'Metal : wood $= 3 : 5$ and wood : plastic $= 2 : 1$. Find metal : plastic in simplest form. Write $a:b$.',
      marks: 3,
      answer: '6:5',
      solution: [
        'Wood LCM of 5 and 2 is 10.',
        'Metal : wood $= 6 : 10$, wood : plastic $= 10 : 5$.',
        'Metal : plastic $= 6 : 5$.',
      ],
    }),
    numeric({
      id: 'r-p15',
      skill: 'Sharing in a ratio',
      prompt: 'A profit of £540 is shared between Asha, Ben and Cai in the ratio $4 : 3 : 2$. How much more does Asha receive than Cai, in pounds?',
      marks: 3,
      answer: '120',
      solution: [
        '9 parts $= £60$ each.',
        'Asha $240$, Cai $120$. Difference $= 120$.',
      ],
    }),
    numeric({
      id: 'r-p16',
      skill: 'Finding a part',
      tier: 'H',
      prompt: 'In a bag of beads, red : blue $= 5 : 2$. There are 21 more red beads than blue beads. How many beads are there in total?',
      marks: 3,
      answer: '49',
      solution: ['3 parts $= 21$, so 1 part $= 7$. Total parts $= 7$, total beads $= 49$.'],
    }),
  ],
  test: {
    durationMinutes: 20,
    questions: [
      numeric({
        id: 'r-t1',
        skill: 'Simplifying ratios',
        prompt: 'Simplify $21 : 35$. Write $a:b$.',
        marks: 1,
        answer: '3:5',
        solution: ['HCF 7: $3 : 5$.'],
      }),
      numeric({
        id: 'r-t2',
        skill: 'Sharing in a ratio',
        prompt: 'Share £90 in the ratio $2 : 7$. What is the larger share, in pounds?',
        marks: 2,
        answer: '70',
        solution: ['9 parts $= £10$. Larger $= 70$.'],
      }),
      numeric({
        id: 'r-t3',
        skill: 'Finding a part',
        prompt: 'A ratio is $3 : 8$. The first quantity is 15. What is the second quantity?',
        marks: 2,
        answer: '40',
        solution: ['1 part $= 5$. Second $= 40$.'],
      }),
      numeric({
        id: 'r-t4',
        skill: 'Sharing in a ratio',
        prompt: 'Share 180 in the ratio $1 : 4 : 5$. What is the middle share?',
        marks: 2,
        answer: '72',
        solution: ['10 parts $= 18$. Middle $= 4 \\times 18 = 72$.'],
      }),
      numeric({
        id: 'r-t5',
        skill: 'Simplifying ratios',
        prompt: 'Write $50\\text{ cm} : 2\\text{ m}$ in simplest form as $a:b$.',
        marks: 2,
        answer: '1:4',
        solution: ['$2\\text{ m} = 200\\text{ cm}$. $50 : 200 = 1 : 4$.'],
      }),
      numeric({
        id: 'r-t6',
        skill: 'Finding a part',
        prompt: 'Two teams share points in the ratio $5 : 2$. Team A has 18 more points than team B. How many points does team A have?',
        marks: 3,
        answer: '30',
        solution: ['3 parts $= 18$, 1 part $= 6$. Team A $= 30$.'],
      }),
      numeric({
        id: 'r-t7',
        skill: 'Sharing in a ratio',
        prompt: 'Orange squash is mixed $1 : 6$ with water. How much water is needed with 40 ml of squash? Give millilitres.',
        marks: 2,
        answer: '240',
        solution: ['Water is 6 parts $= 240$ ml.'],
      }),
      numeric({
        id: 'r-t8',
        skill: 'Combining ratios',
        tier: 'H',
        prompt: '$P : Q = 3 : 4$ and $Q : R = 5 : 2$. Find $P : R$ as $a:b$ in simplest form.',
        marks: 3,
        answer: '15:8',
        solution: [
          'Q LCM of 4 and 5 is 20.',
          '$P : Q = 15 : 20$, $Q : R = 20 : 8$.',
          '$P : R = 15 : 8$.',
        ],
      }),
      numeric({
        id: 'r-t9',
        skill: 'Finding a part',
        prompt: 'In a class, girls : boys $= 4 : 5$. 25 students are boys. How many students are in the class?',
        marks: 3,
        answer: '45',
        solution: ['5 parts $= 25$, so 1 part $= 5$. Total 9 parts $= 45$.'],
      }),
    ],
  },
}
