/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormulasRouteImport } from './routes/formulas'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as MocksRouteImport } from './routes/mocks'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'
import { Route as MocksMockIdRouteImport } from './routes/mocks_.$mockId'
import { Route as ChaptersSlugIndexRouteImport } from './routes/chapters.$slug.index'
import { Route as ChaptersSlugPracticeRouteImport } from './routes/chapters.$slug.practice'
import { Route as ChaptersSlugResultsRouteImport } from './routes/chapters.$slug.results'
import { Route as ChaptersSlugTestRouteImport } from './routes/chapters.$slug.test'
import { Route as ChaptersSlugTheoryRouteImport } from './routes/chapters.$slug.theory'
import { Route as MocksMockIdReviewRouteImport } from './routes/mocks_.$mockId.review'
import { Route as MocksMockIdSitPaperIdRouteImport } from './routes/mocks_.$mockId.sit.$paperId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulasRoute = FormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const MocksRoute = MocksRouteImport.update({
  id: '/mocks',
  path: '/mocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/chapters/$slug',
  path: '/chapters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MocksMockIdRoute = MocksMockIdRouteImport.update({
  id: '/mocks_/$mockId',
  path: '/mocks/$mockId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugIndexRoute = ChaptersSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChaptersSlugRoute,
} as any)
const ChaptersSlugPracticeRoute = ChaptersSlugPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => ChaptersSlugRoute,
} as any)
const ChaptersSlugResultsRoute = ChaptersSlugResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ChaptersSlugRoute,
} as any)
const ChaptersSlugTestRoute = ChaptersSlugTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ChaptersSlugRoute,
} as any)
const ChaptersSlugTheoryRoute = ChaptersSlugTheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => ChaptersSlugRoute,
} as any)
const MocksMockIdReviewRoute = MocksMockIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => MocksMockIdRoute,
} as any)
const MocksMockIdSitPaperIdRoute = MocksMockIdSitPaperIdRouteImport.update({
  id: '/sit/$paperId',
  path: '/sit/$paperId',
  getParentRoute: () => MocksMockIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formulas': typeof FormulasRoute
  '/library': typeof LibraryRoute
  '/mocks': typeof MocksRoute
  '/progress': typeof ProgressRoute
  '/chapters/$slug': typeof ChaptersSlugRouteWithChildren
  '/mocks/$mockId': typeof MocksMockIdRouteWithChildren
  '/chapters/$slug/practice': typeof ChaptersSlugPracticeRoute
  '/chapters/$slug/results': typeof ChaptersSlugResultsRoute
  '/chapters/$slug/test': typeof ChaptersSlugTestRoute
  '/chapters/$slug/theory': typeof ChaptersSlugTheoryRoute
  '/mocks/$mockId/review': typeof MocksMockIdReviewRoute
  '/chapters/$slug/': typeof ChaptersSlugIndexRoute
  '/mocks/$mockId/sit/$paperId': typeof MocksMockIdSitPaperIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formulas': typeof FormulasRoute
  '/library': typeof LibraryRoute
  '/mocks': typeof MocksRoute
  '/progress': typeof ProgressRoute
  '/mocks/$mockId': typeof MocksMockIdRouteWithChildren
  '/chapters/$slug/practice': typeof ChaptersSlugPracticeRoute
  '/chapters/$slug/results': typeof ChaptersSlugResultsRoute
  '/chapters/$slug/test': typeof ChaptersSlugTestRoute
  '/chapters/$slug/theory': typeof ChaptersSlugTheoryRoute
  '/mocks/$mockId/review': typeof MocksMockIdReviewRoute
  '/chapters/$slug': typeof ChaptersSlugIndexRoute
  '/mocks/$mockId/sit/$paperId': typeof MocksMockIdSitPaperIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formulas': typeof FormulasRoute
  '/library': typeof LibraryRoute
  '/mocks': typeof MocksRoute
  '/progress': typeof ProgressRoute
  '/chapters/$slug': typeof ChaptersSlugRouteWithChildren
  '/mocks_/$mockId': typeof MocksMockIdRouteWithChildren
  '/chapters/$slug/practice': typeof ChaptersSlugPracticeRoute
  '/chapters/$slug/results': typeof ChaptersSlugResultsRoute
  '/chapters/$slug/test': typeof ChaptersSlugTestRoute
  '/chapters/$slug/theory': typeof ChaptersSlugTheoryRoute
  '/mocks_/$mockId/review': typeof MocksMockIdReviewRoute
  '/chapters/$slug/': typeof ChaptersSlugIndexRoute
  '/mocks_/$mockId/sit/$paperId': typeof MocksMockIdSitPaperIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/formulas'
    | '/library'
    | '/mocks'
    | '/progress'
    | '/chapters/$slug'
    | '/mocks/$mockId'
    | '/chapters/$slug/practice'
    | '/chapters/$slug/results'
    | '/chapters/$slug/test'
    | '/chapters/$slug/theory'
    | '/mocks/$mockId/review'
    | '/chapters/$slug/'
    | '/mocks/$mockId/sit/$paperId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/formulas'
    | '/library'
    | '/mocks'
    | '/progress'
    | '/mocks/$mockId'
    | '/chapters/$slug/practice'
    | '/chapters/$slug/results'
    | '/chapters/$slug/test'
    | '/chapters/$slug/theory'
    | '/mocks/$mockId/review'
    | '/chapters/$slug'
    | '/mocks/$mockId/sit/$paperId'
  id:
    | '__root__'
    | '/'
    | '/formulas'
    | '/library'
    | '/mocks'
    | '/progress'
    | '/chapters/$slug'
    | '/mocks_/$mockId'
    | '/chapters/$slug/practice'
    | '/chapters/$slug/results'
    | '/chapters/$slug/test'
    | '/chapters/$slug/theory'
    | '/mocks_/$mockId/review'
    | '/chapters/$slug/'
    | '/mocks_/$mockId/sit/$paperId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormulasRoute: typeof FormulasRoute
  LibraryRoute: typeof LibraryRoute
  MocksRoute: typeof MocksRoute
  ProgressRoute: typeof ProgressRoute
  ChaptersSlugRoute: typeof ChaptersSlugRouteWithChildren
  MocksMockIdRoute: typeof MocksMockIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulas': {
      id: '/formulas'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof FormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mocks': {
      id: '/mocks'
      path: '/mocks'
      fullPath: '/mocks'
      preLoaderRoute: typeof MocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/chapters/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mocks_/$mockId': {
      id: '/mocks_/$mockId'
      path: '/mocks/$mockId'
      fullPath: '/mocks/$mockId'
      preLoaderRoute: typeof MocksMockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug/': {
      id: '/chapters/$slug/'
      path: '/'
      fullPath: '/chapters/$slug/'
      preLoaderRoute: typeof ChaptersSlugIndexRouteImport
      parentRoute: typeof ChaptersSlugRoute
    }
    '/chapters/$slug/practice': {
      id: '/chapters/$slug/practice'
      path: '/practice'
      fullPath: '/chapters/$slug/practice'
      preLoaderRoute: typeof ChaptersSlugPracticeRouteImport
      parentRoute: typeof ChaptersSlugRoute
    }
    '/chapters/$slug/results': {
      id: '/chapters/$slug/results'
      path: '/results'
      fullPath: '/chapters/$slug/results'
      preLoaderRoute: typeof ChaptersSlugResultsRouteImport
      parentRoute: typeof ChaptersSlugRoute
    }
    '/chapters/$slug/test': {
      id: '/chapters/$slug/test'
      path: '/test'
      fullPath: '/chapters/$slug/test'
      preLoaderRoute: typeof ChaptersSlugTestRouteImport
      parentRoute: typeof ChaptersSlugRoute
    }
    '/chapters/$slug/theory': {
      id: '/chapters/$slug/theory'
      path: '/theory'
      fullPath: '/chapters/$slug/theory'
      preLoaderRoute: typeof ChaptersSlugTheoryRouteImport
      parentRoute: typeof ChaptersSlugRoute
    }
    '/mocks_/$mockId/review': {
      id: '/mocks_/$mockId/review'
      path: '/review'
      fullPath: '/mocks/$mockId/review'
      preLoaderRoute: typeof MocksMockIdReviewRouteImport
      parentRoute: typeof MocksMockIdRoute
    }
    '/mocks_/$mockId/sit/$paperId': {
      id: '/mocks_/$mockId/sit/$paperId'
      path: '/sit/$paperId'
      fullPath: '/mocks/$mockId/sit/$paperId'
      preLoaderRoute: typeof MocksMockIdSitPaperIdRouteImport
      parentRoute: typeof MocksMockIdRoute
    }
  }
}

interface ChaptersSlugRouteChildren {
  ChaptersSlugPracticeRoute: typeof ChaptersSlugPracticeRoute
  ChaptersSlugResultsRoute: typeof ChaptersSlugResultsRoute
  ChaptersSlugTestRoute: typeof ChaptersSlugTestRoute
  ChaptersSlugTheoryRoute: typeof ChaptersSlugTheoryRoute
  ChaptersSlugIndexRoute: typeof ChaptersSlugIndexRoute
}

const ChaptersSlugRouteChildren: ChaptersSlugRouteChildren = {
  ChaptersSlugPracticeRoute: ChaptersSlugPracticeRoute,
  ChaptersSlugResultsRoute: ChaptersSlugResultsRoute,
  ChaptersSlugTestRoute: ChaptersSlugTestRoute,
  ChaptersSlugTheoryRoute: ChaptersSlugTheoryRoute,
  ChaptersSlugIndexRoute: ChaptersSlugIndexRoute,
}

const ChaptersSlugRouteWithChildren = ChaptersSlugRoute._addFileChildren(
  ChaptersSlugRouteChildren,
)

interface MocksMockIdRouteChildren {
  MocksMockIdReviewRoute: typeof MocksMockIdReviewRoute
  MocksMockIdSitPaperIdRoute: typeof MocksMockIdSitPaperIdRoute
}

const MocksMockIdRouteChildren: MocksMockIdRouteChildren = {
  MocksMockIdReviewRoute: MocksMockIdReviewRoute,
  MocksMockIdSitPaperIdRoute: MocksMockIdSitPaperIdRoute,
}

const MocksMockIdRouteWithChildren = MocksMockIdRoute._addFileChildren(
  MocksMockIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormulasRoute: FormulasRoute,
  LibraryRoute: LibraryRoute,
  MocksRoute: MocksRoute,
  ProgressRoute: ProgressRoute,
  ChaptersSlugRoute: ChaptersSlugRouteWithChildren,
  MocksMockIdRoute: MocksMockIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
