import { mc, multi, numeric } from '../make'
import type { ExamMock } from '../../lib/types'

const paper1 = [
  multi({
    id: 'gcse1-1',
    skill: 'Number',
    ao: 1,
    chapter: 1,
    prompt: 'This question is about place value and directed numbers.',
    parts: [
      {
        id: 'gcse1-1a',
        label: 'a',
        prompt: 'Write $2.07 \\times 10^3$ as an ordinary number.',
        marks: 1,
        answer: '2070',
        accepted: ['2,070'],
        solution: ['$2.07 \\times 1000 = 2070$.'],
      },
      {
        id: 'gcse1-1b',
        label: 'b',
        prompt: 'Work out $-12 \\div 4 + -5 \\times 2$.',
        marks: 2,
        answer: '-13',
        solution: ['$-12 \\div 4 = -3$ and $-5 \\times 2 = -10$. Then $-3 + -10 = -13$.'],
      },
    ],
  }),
  multi({
    id: 'gcse1-2',
    skill: 'Fractions',
    ao: 1,
    chapter: 4,
    prompt: 'Calculate with fractions.',
    parts: [
      {
        id: 'gcse1-2a',
        label: 'a',
        prompt: 'Work out $1\\dfrac{3}{8} + \\dfrac{5}{6}$.',
        marks: 3,
        answer: '53/24',
        accepted: ['2 5/24'],
        solution: ['$\\dfrac{11}{8} + \\dfrac{5}{6} = \\dfrac{33}{24} + \\dfrac{20}{24} = \\dfrac{53}{24}$.'],
      },
      {
        id: 'gcse1-2b',
        label: 'b',
        prompt: 'Find $\\dfrac{5}{12}$ of 96.',
        marks: 2,
        answer: '40',
        solution: ['$96 \\div 12 \\times 5 = 40$.'],
      },
    ],
  }),
  numeric({
    id: 'gcse1-3',
    skill: 'Percentages',
    ao: 2,
    chapter: 5,
    prompt: 'A price of £64 is reduced by $12.5\\%$. Find the new price, in pounds.',
    marks: 3,
    answer: '56',
    solution: ['$12.5\\%$ of 64 is 8, so $64-8=56$.'],
  }),
  multi({
    id: 'gcse1-4',
    skill: 'Algebra',
    ao: 1,
    chapter: 10,
    prompt: 'Expand and factorise.',
    parts: [
      {
        id: 'gcse1-4a',
        label: 'a',
        prompt: 'Expand and simplify $5(x-2) + 3(2x+1)$.',
        marks: 2,
        answer: '11x-7',
        accepted: ['11x - 7'],
        solution: ['$5x-10+6x+3=11x-7$.'],
      },
      {
        id: 'gcse1-4b',
        label: 'b',
        prompt: 'Factorise $x^2 - 9$.',
        marks: 2,
        answer: '(x-3)(x+3)',
        accepted: ['(x+3)(x-3)', '(x - 3)(x + 3)'],
        solution: ['Difference of two squares: $(x-3)(x+3)$.'],
      },
    ],
  }),
  numeric({
    id: 'gcse1-5',
    skill: 'Linear equations',
    ao: 1,
    chapter: 11,
    prompt: 'Solve $6x - 5 = 2(x + 7)$.',
    marks: 3,
    answer: '4.75',
    accepted: ['19/4', '4 3/4'],
    solution: ['$6x-5=2x+14$, so $4x=19$ and $x=\\dfrac{19}{4}$.'],
  }),
  multi({
    id: 'gcse1-6',
    skill: 'Ratio',
    ao: 2,
    chapter: 17,
    prompt: 'A drink is made from juice and water in the ratio $3 : 7$. A jug holds $1.5$ litres of the drink.',
    parts: [
      {
        id: 'gcse1-6a',
        label: 'a',
        prompt: 'How many litres of juice are in the jug?',
        marks: 2,
        answer: '0.45',
        accepted: ['9/20'],
        solution: ['Parts total 10. Juice $= \\dfrac{3}{10} \\times 1.5 = 0.45$ litres.'],
      },
      {
        id: 'gcse1-6b',
        label: 'b',
        prompt: 'Another $0.3$ litres of water is added. Write the new juice : water ratio in its simplest form.',
        marks: 3,
        answer: '1:3',
        accepted: ['1 : 3', '0.45:1.35'],
        solution: ['Water was $1.05$ litres and becomes $1.35$. Juice stays $0.45$. $0.45:1.35 = 1:3$.'],
      },
    ],
  }),
  numeric({
    id: 'gcse1-7',
    skill: 'Angles',
    ao: 2,
    chapter: 21,
    prompt: 'The interior angle of a regular polygon is $150^\\circ$. How many sides does it have?',
    marks: 3,
    answer: '12',
    solution: ['Exterior angle $30^\\circ$. Number of sides $360 \\div 30 = 12$.'],
  }),
  numeric({
    id: 'gcse1-8',
    skill: 'Pythagoras',
    ao: 2,
    chapter: 24,
    prompt: 'A right-angled triangle has sides $20\\,\\text{cm}$ and $21\\,\\text{cm}$ enclosing the right angle. Find the hypotenuse in centimetres.',
    marks: 3,
    answer: '29',
    solution: ['$20^2 + 21^2 = 400 + 441 = 841$. Hypotenuse $= \\sqrt{841} = 29$.'],
  }),
  numeric({
    id: 'gcse1-9',
    skill: 'Probability',
    ao: 2,
    chapter: 28,
    prompt:
      'A spinner has 8 equal sections: 3 red, 3 blue and 2 green. Find the probability of red or green, as a fraction.',
    marks: 2,
    answer: '5/8',
    solution: ['Red or green: 5 sections out of 8.'],
  }),
  multi({
    id: 'gcse1-10',
    skill: 'Averages',
    ao: 3,
    chapter: 30,
    prompt: 'Seven ages are $11, 13, 13, 14, 16, 18, 20$.',
    parts: [
      {
        id: 'gcse1-10a',
        label: 'a',
        prompt: 'Find the median.',
        marks: 1,
        answer: '14',
        solution: ['The 4th value is 14.'],
      },
      {
        id: 'gcse1-10b',
        label: 'b',
        prompt: 'Find the range.',
        marks: 1,
        answer: '9',
        solution: ['$20-11=9$.'],
      },
      {
        id: 'gcse1-10c',
        label: 'c',
        prompt: 'Find the mean.',
        marks: 2,
        answer: '15',
        solution: ['Sum $105$. Mean $105 \\div 7 = 15$.'],
      },
    ],
  }),
  numeric({
    id: 'gcse1-11',
    skill: 'Area',
    ao: 3,
    chapter: 23,
    prompt:
      'A parallelogram has base $11\\,\\text{cm}$ and perpendicular height $8\\,\\text{cm}$. Find its area in cm$^2$.',
    marks: 2,
    answer: '88',
    solution: ['Area $=$ base $\\times$ height $= 88$.'],
  }),
  numeric({
    id: 'gcse1-12',
    skill: 'Sequences',
    ao: 2,
    chapter: 14,
    prompt: 'The $n$th term of a sequence is $3n + 11$. Find the first term that is greater than 50.',
    marks: 3,
    answer: '53',
    solution: ['$3n+11>50$, $3n>39$, $n>13$. The 14th term is $3\\times 14+11=53$.'],
  }),
  numeric({
    id: 'gcse1-13',
    skill: 'Inequalities',
    ao: 1,
    chapter: 13,
    prompt: 'Solve $4x + 7 \\ge 19$. Give the critical value that $x$ is greater than or equal to.',
    marks: 2,
    answer: '3',
    solution: ['$4x \\ge 12$, so $x \\ge 3$.'],
  }),
  numeric({
    id: 'gcse1-14',
    skill: 'Proportion',
    ao: 3,
    chapter: 18,
    prompt: 'A recipe for 10 biscuits uses $250\\,\\text{g}$ of butter. How many grams are needed for 16 biscuits?',
    marks: 3,
    answer: '400',
    solution: ['One biscuit uses $25\\,\\text{g}$. Sixteen use $400\\,\\text{g}$.'],
  }),
  numeric({
    id: 'gcse1-15',
    skill: 'Indices',
    ao: 1,
    chapter: 7,
    prompt: 'Work out $5^3 - 4^3$.',
    marks: 2,
    answer: '61',
    solution: ['$125 - 64 = 61$.'],
  }),
  numeric({
    id: 'gcse1-19',
    skill: 'Decimals',
    ao: 1,
    chapter: 6,
    prompt: 'Work out $4.5 \\times 0.6$.',
    marks: 2,
    answer: '2.7',
    solution: ['$45 \\times 6 = 270$, then 2 decimal places: $2.70 = 2.7$.'],
  }),
  numeric({
    id: 'gcse1-20',
    skill: 'Expressions',
    ao: 1,
    chapter: 9,
    prompt: 'Simplify $2x + 5x - 3x$.',
    marks: 1,
    answer: '4x',
    solution: ['$2+5-3=4$, so $4x$.'],
  }),
  numeric({
    id: 'gcse1-21',
    skill: 'HCF',
    ao: 1,
    chapter: 3,
    prompt: 'Find the LCM of 6 and 15.',
    marks: 2,
    answer: '30',
    solution: ['Multiples of 15: 15, 30… 30 is also a multiple of 6.'],
  }),
  numeric({
    id: 'gcse1-22',
    skill: 'Percentages',
    ao: 2,
    chapter: 5,
    prompt: 'Work out $25\\%$ of 84.',
    marks: 2,
    answer: '21',
    solution: ['$25\\% = \\dfrac{1}{4}$, and $84 \\div 4 = 21$.'],
  }),
  numeric({
    id: 'gcse1-23',
    skill: 'Perimeter',
    ao: 2,
    chapter: 23,
    prompt: 'A square has side $9\\,\\text{cm}$. Find its perimeter in centimetres.',
    marks: 1,
    answer: '36',
    solution: ['$4 \\times 9 = 36$.'],
  }),
  multi({
    id: 'gcse1-16',
    skill: 'Simultaneous',
    ao: 2,
    chapter: 16,
    tier: 'H',
    prompt: 'Solve $5x + 2y = 24$ and $3x - 2y = 8$.',
    parts: [
      {
        id: 'gcse1-16a',
        label: 'a',
        prompt: 'Find $x$.',
        marks: 2,
        answer: '4',
        solution: ['Add: $8x = 32$, so $x = 4$.'],
      },
      {
        id: 'gcse1-16b',
        label: 'b',
        prompt: 'Find $y$.',
        marks: 2,
        answer: '2',
        solution: ['$5\\times 4 + 2y = 24$, so $20+2y=24$ and $y=2$.'],
      },
    ],
  }),
  numeric({
    id: 'gcse1-17',
    skill: 'Standard form',
    ao: 1,
    chapter: 8,
    tier: 'H',
    prompt: 'Work out $(8 \\times 10^6) \\div (2 \\times 10^{-2})$. Give your answer in standard form.',
    marks: 2,
    answer: '4 x 10^8',
    accepted: ['4×10^8', '4e8', '400000000'],
    placeholder: 'e.g. 4 x 10^8',
    solution: ['$8 \\div 2 = 4$ and $10^{6-(-2)}=10^8$, so $4 \\times 10^8$.'],
  }),
  numeric({
    id: 'gcse1-18',
    skill: 'Graphs',
    ao: 3,
    chapter: 15,
    tier: 'H',
    prompt: 'The line $y = \\dfrac{1}{2}x + 3$ passes through $(6, k)$. Find $k$.',
    marks: 2,
    answer: '6',
    solution: ['$k = \\dfrac{1}{2}\\times 6 + 3 = 6$.'],
  }),
]

const paper2 = [
  numeric({
    id: 'gcse2-1',
    skill: 'Reverse percentages',
    ao: 2,
    chapter: 5,
    prompt: 'A laptop is sold for £486 after a $10\\%$ discount. What was the original price, in pounds?',
    marks: 3,
    answer: '540',
    solution: ['£486 is $90\\%$ of the original. $486 \\div 0.9 = 540$.'],
  }),
  numeric({
    id: 'gcse2-2',
    skill: 'Compound interest',
    ao: 2,
    chapter: 5,
    prompt:
      '£1600 is invested at $3.5\\%$ compound interest for 2 years. Find the value after 2 years, in pounds, to the nearest penny.',
    marks: 3,
    answer: '1713.96',
    tolerance: 0.02,
    solution: ['$1600 \\times 1.035^2 = 1600 \\times 1.071225 = 1713.96$.'],
  }),
  multi({
    id: 'gcse2-3',
    skill: 'Trigonometry',
    ao: 2,
    chapter: 25,
    prompt: 'In right-angled triangle $XYZ$, $\\angle Z = 90^\\circ$, $YZ = 11\\,\\text{cm}$ and $XZ = 7\\,\\text{cm}$.',
    parts: [
      {
        id: 'gcse2-3a',
        label: 'a',
        prompt: 'Find $XY$, in centimetres, to 1 decimal place.',
        marks: 2,
        answer: '13.0',
        accepted: ['13'],
        tolerance: 0.15,
        solution: ['$XY = \\sqrt{11^2 + 7^2} = \\sqrt{170} \\approx 13.04$, so $13.0$ to 1 d.p.'],
      },
      {
        id: 'gcse2-3b',
        label: 'b',
        prompt: 'Find $\\angle X$, in degrees, to 1 decimal place.',
        marks: 3,
        answer: '57.5',
        tolerance: 0.2,
        solution: ['$\\tan X = \\dfrac{11}{7}$. $X = \\tan^{-1}(11/7) \\approx 57.5^\\circ$.'],
      },
    ],
  }),
  multi({
    id: 'gcse2-4',
    skill: 'Circles',
    ao: 2,
    chapter: 27,
    prompt: 'A circle has radius $5.5\\,\\text{cm}$.',
    parts: [
      {
        id: 'gcse2-4a',
        label: 'a',
        prompt: 'Find the circumference, to 1 decimal place.',
        marks: 2,
        answer: '34.6',
        tolerance: 0.2,
        solution: ['$C = 11\\pi \\approx 34.56$, so $34.6$ to 1 d.p.'],
      },
      {
        id: 'gcse2-4b',
        label: 'b',
        prompt: 'Find the area, to 1 decimal place.',
        marks: 2,
        answer: '95.0',
        accepted: ['95'],
        tolerance: 0.3,
        solution: ['$A = 30.25\\pi \\approx 95.03$, so $95.0$ to 1 d.p.'],
      },
    ],
  }),
  numeric({
    id: 'gcse2-5',
    skill: 'Speed',
    ao: 2,
    chapter: 19,
    prompt: 'A bus travels $84\\,\\text{km}$ in 1 hour 10 minutes. Find the average speed in km/h.',
    marks: 3,
    answer: '72',
    solution: ['1 hour 10 minutes $= \\dfrac{7}{6}$ hours. Speed $= 84 \\div \\dfrac{7}{6} = 84 \\times \\dfrac{6}{7} = 72$.'],
  }),
  multi({
    id: 'gcse2-6',
    skill: 'Averages',
    ao: 2,
    chapter: 30,
    prompt: 'Grouped times (minutes): 0–10 (5 people), 10–20 (9 people), 20–30 (6 people).',
    parts: [
      {
        id: 'gcse2-6a',
        label: 'a',
        prompt: 'Which class contains the median?',
        marks: 1,
        answer: '10-20',
        accepted: ['10–20', '10 to 20'],
        solution: ['20 people, so the median is the 10th value, which lies in 10–20.'],
      },
      {
        id: 'gcse2-6b',
        label: 'b',
        prompt: 'Estimate the mean time, in minutes.',
        marks: 4,
        answer: '15.5',
        tolerance: 0.1,
        solution: [
          'Midpoints 5, 15 and 25.',
          'Total $= 5\\times 5 + 9\\times 15 + 6\\times 25 = 25+135+150=310$.',
          'Mean $= 310 \\div 20 = 15.5$.',
        ],
      },
    ],
  }),
  numeric({
    id: 'gcse2-7',
    skill: 'Density',
    ao: 3,
    chapter: 19,
    prompt: 'A steel bar has volume $40\\,\\text{cm}^3$ and density $7.8\\,\\text{g/cm}^3$. Find its mass in grams.',
    marks: 2,
    answer: '312',
    solution: ['Mass $= 7.8 \\times 40 = 312$ g.'],
  }),
  numeric({
    id: 'gcse2-8',
    skill: 'Volume',
    ao: 2,
    chapter: 23,
    prompt: 'A cuboid tank is $1.2\\,\\text{m}$ by $0.8\\,\\text{m}$ by $0.5\\,\\text{m}$. Find its capacity in litres.',
    marks: 3,
    answer: '480',
    solution: ['Volume $0.48\\,\\text{m}^3 = 480$ litres.'],
  }),
  numeric({
    id: 'gcse2-9',
    skill: 'Scale',
    ao: 2,
    chapter: 20,
    prompt: 'A plan uses a scale of $1:200$. A room is $8.4\\,\\text{m}$ long. How long is it on the plan, in centimetres?',
    marks: 3,
    answer: '4.2',
    solution: ['$8.4\\,\\text{m} = 840\\,\\text{cm}$. Plan length $840 \\div 200 = 4.2\\,\\text{cm}$.'],
  }),
  numeric({
    id: 'gcse2-10',
    skill: 'Formulae',
    ao: 1,
    chapter: 12,
    prompt: 'The formula $F = \\dfrac{9}{5}C + 32$ converts Celsius to Fahrenheit. Find $F$ when $C = 25$.',
    marks: 2,
    answer: '77',
    solution: ['$F = \\dfrac{9}{5}\\times 25 + 32 = 45 + 32 = 77$.'],
  }),
  mc({
    id: 'gcse2-11',
    skill: 'Transformations',
    ao: 1,
    chapter: 26,
    prompt: 'Point $(2, 5)$ is rotated $90^\\circ$ clockwise about the origin. What is the image?',
    marks: 2,
    choices: ['$(5, -2)$', '$(-5, 2)$', '$(-2, -5)$', '$(5, 2)$'],
    correctIndex: 0,
    solution: ['A $90^\\circ$ clockwise rotation about the origin sends $(x,y)$ to $(y,-x)$, so $(2,5)$ maps to $(5,-2)$.'],
  }),
  numeric({
    id: 'gcse2-12',
    skill: 'FDP',
    ao: 1,
    chapter: 6,
    prompt: 'Write $\\dfrac{7}{20}$ as a percentage.',
    marks: 2,
    answer: '35',
    accepted: ['35%'],
    solution: ['$\\dfrac{7}{20} = 0.35 = 35\\%$.'],
  }),
  numeric({
    id: 'gcse2-13',
    skill: 'Probability',
    ao: 3,
    chapter: 29,
    prompt:
      'A fair coin is flipped and a fair 6-sided dice is rolled. Find the probability of heads and a multiple of 3, as a fraction.',
    marks: 3,
    answer: '1/6',
    accepted: ['2/12'],
    solution: ['$P(\\text{heads})=\\dfrac{1}{2}$ and $P(3\\text{ or }6)=\\dfrac{2}{6}=\\dfrac{1}{3}$. Product $\\dfrac{1}{6}$.'],
  }),
  numeric({
    id: 'gcse2-14',
    skill: 'Area problem',
    ao: 3,
    chapter: 23,
    prompt:
      'A lawn is $16\\,\\text{m}$ by $9\\,\\text{m}$. A $0.5\\,\\text{m}$ path runs around the inside edge. Find the remaining grass area, in m$^2$.',
    marks: 4,
    answer: '120',
    solution: [
      'Inner rectangle is $15\\,\\text{m}$ by $8\\,\\text{m}$.',
      'Area $120$.',
    ],
  }),
  numeric({
    id: 'gcse2-18',
    skill: 'Percentages',
    ao: 1,
    chapter: 5,
    prompt: 'Work out $8\\%$ of 150.',
    marks: 2,
    answer: '12',
    solution: ['$10\\% = 15$ and $1\\% = 1.5$, so $8\\% = 12$. Or $0.08 \\times 150 = 12$.'],
  }),
  numeric({
    id: 'gcse2-19',
    skill: 'Ratio',
    ao: 2,
    chapter: 17,
    prompt: 'Share 45 in the ratio $2 : 7$. What is the smaller share?',
    marks: 2,
    answer: '10',
    solution: ['Parts total 9. Smaller share $2 \\times 5 = 10$.'],
  }),
  numeric({
    id: 'gcse2-20',
    skill: 'Linear equations',
    ao: 1,
    chapter: 11,
    prompt: 'Solve $3x + 11 = 32$.',
    marks: 2,
    answer: '7',
    solution: ['$3x = 21$, so $x = 7$.'],
  }),
  numeric({
    id: 'gcse2-21',
    skill: 'Decimals',
    ao: 1,
    chapter: 6,
    prompt: 'Work out $12.5 \\times 0.4$.',
    marks: 2,
    answer: '5',
    solution: ['$125 \\times 4 = 500$, then 2 decimal places: $5.00$.'],
  }),
  numeric({
    id: 'gcse2-15',
    skill: 'Standard form',
    ao: 1,
    chapter: 8,
    tier: 'H',
    prompt: 'Work out $(9.6 \\times 10^4) - (1.4 \\times 10^4)$. Give your answer in standard form.',
    marks: 2,
    answer: '8.2 x 10^4',
    accepted: ['8.2×10^4', '8.2e4', '82000'],
    placeholder: 'e.g. 8.2 x 10^4',
    solution: ['$9.6-1.4=8.2$, so $8.2 \\times 10^4$.'],
  }),
  numeric({
    id: 'gcse2-16',
    skill: 'Rearranging',
    ao: 2,
    chapter: 12,
    tier: 'H',
    prompt: 'Make $x$ the subject of $y = \\dfrac{2x-1}{5}$. Write an expression such as (5y+1)/2.',
    marks: 3,
    answer: '(5y+1)/2',
    accepted: ['(5y + 1)/2'],
    placeholder: 'e.g. (5y+1)/2',
    solution: ['$5y=2x-1$, so $2x=5y+1$ and $x=\\dfrac{5y+1}{2}$.'],
  }),
  numeric({
    id: 'gcse2-17',
    skill: 'Trigonometry',
    ao: 3,
    chapter: 25,
    tier: 'H',
    prompt:
      'From a point $80\\,\\text{m}$ from a tower, the angle of elevation to the top is $38^\\circ$. Find the height of the tower, in metres, to the nearest metre.',
    marks: 3,
    answer: '62',
    tolerance: 2,
    solution: ['$h = 80\\tan 38^\\circ \\approx 62.48$, so $62$ m to the nearest metre.'],
  }),
]

const paper3 = [
  multi({
    id: 'gcse3-1',
    skill: 'Percentages',
    ao: 3,
    chapter: 5,
    prompt: 'A bicycle costs £320. In a sale it is reduced by $15\\%$, then a further £20 is taken off.',
    parts: [
      {
        id: 'gcse3-1a',
        label: 'a',
        prompt: 'Find the price after the $15\\%$ reduction, in pounds.',
        marks: 2,
        answer: '272',
        solution: ['$320 \\times 0.85 = 272$.'],
      },
      {
        id: 'gcse3-1b',
        label: 'b',
        prompt: 'Find the final price, in pounds.',
        marks: 1,
        answer: '252',
        solution: ['$272-20=252$.'],
      },
    ],
  }),
  numeric({
    id: 'gcse3-2',
    skill: 'Ratio',
    ao: 3,
    chapter: 17,
    prompt:
      'Dan and Eve share some money in the ratio $5 : 8$. Eve receives £60 more than Dan. How much does Dan receive, in pounds?',
    marks: 4,
    answer: '100',
    solution: [
      'The difference is 3 parts, which is £60. One part is £20.',
      'Dan receives $5 \\times 20 = 100$.',
    ],
  }),
  multi({
    id: 'gcse3-3',
    skill: 'Algebra',
    ao: 1,
    chapter: 11,
    prompt: 'Solve these equations.',
    parts: [
      {
        id: 'gcse3-3a',
        label: 'a',
        prompt: 'Solve $9 - 4x = 1$.',
        marks: 2,
        answer: '2',
        solution: ['$-4x = -8$, so $x = 2$.'],
      },
      {
        id: 'gcse3-3b',
        label: 'b',
        prompt: 'Solve $\\dfrac{2x+3}{5} = x - 1$.',
        marks: 3,
        answer: '8/3',
        accepted: ['2.667', '2.67', '2 2/3'],
        tolerance: 0.02,
        solution: ['$2x+3=5x-5$, so $8=3x$ and $x=\\dfrac{8}{3}$.'],
      },
    ],
  }),
  numeric({
    id: 'gcse3-4',
    skill: 'Pythagoras',
    ao: 3,
    chapter: 24,
    prompt:
      'A ramp is $2.4\\,\\text{m}$ long and rises $0.7\\,\\text{m}$. How far does it run horizontally, in metres?',
    marks: 3,
    answer: '2.3',
    tolerance: 0.05,
    solution: ['$\\sqrt{2.4^2 - 0.7^2} = \\sqrt{5.76-0.49} = \\sqrt{5.27} \\approx 2.30$.'],
  }),
  multi({
    id: 'gcse3-5',
    skill: 'Tree diagrams',
    ao: 3,
    chapter: 29,
    prompt: 'A bag contains 3 red and 5 green counters. Two counters are taken at random without replacement.',
    parts: [
      {
        id: 'gcse3-5a',
        label: 'a',
        prompt: 'Find the probability both are green, as a fraction.',
        marks: 2,
        answer: '5/14',
        accepted: ['20/56'],
        solution: ['$\\dfrac{5}{8} \\times \\dfrac{4}{7} = \\dfrac{20}{56} = \\dfrac{5}{14}$.'],
      },
      {
        id: 'gcse3-5b',
        label: 'b',
        prompt: 'Find the probability the two counters are different colours, as a fraction.',
        marks: 3,
        answer: '15/28',
        accepted: ['30/56'],
        solution: [
          'RG: $\\dfrac{3}{8}\\times\\dfrac{5}{7}=\\dfrac{15}{56}$.',
          'GR: $\\dfrac{5}{8}\\times\\dfrac{3}{7}=\\dfrac{15}{56}$.',
          'Total $\\dfrac{30}{56} = \\dfrac{15}{28}$.',
        ],
      },
    ],
  }),
  numeric({
    id: 'gcse3-6',
    skill: 'Circles',
    ao: 3,
    chapter: 27,
    prompt:
      'A circular running track has radius $35\\,\\text{m}$. How far, in metres, is one full lap, to the nearest metre?',
    marks: 3,
    answer: '220',
    tolerance: 2,
    solution: ['$C = 70\\pi \\approx 219.9$, so $220$ m.'],
  }),
  numeric({
    id: 'gcse3-7',
    skill: 'Compound measures',
    ao: 2,
    chapter: 19,
    prompt: 'A force of $450\\,\\text{N}$ acts on an area of $0.18\\,\\text{m}^2$. Find the pressure in N/m$^2$.',
    marks: 2,
    answer: '2500',
    solution: ['Pressure $= 450 \\div 0.18 = 2500$.'],
  }),
  numeric({
    id: 'gcse3-8',
    skill: 'Sequences',
    ao: 2,
    chapter: 14,
    prompt: 'The first four triangular-looking terms of an arithmetic sequence are $4, 10, 16, 22$. Find the 15th term.',
    marks: 2,
    answer: '88',
    solution: ['$n$th term $6n-2$. 15th term $90-2=88$.'],
  }),
  numeric({
    id: 'gcse3-9',
    skill: 'Volume',
    ao: 2,
    chapter: 27,
    prompt: 'A cylinder has diameter $10\\,\\text{cm}$ and height $6\\,\\text{cm}$. Find its volume, to the nearest whole number.',
    marks: 3,
    answer: '471',
    tolerance: 2,
    solution: ['Radius 5. $V = 150\\pi \\approx 471.2$, so $471$.'],
  }),
  numeric({
    id: 'gcse3-10',
    skill: 'Averages',
    ao: 2,
    chapter: 30,
    prompt: 'The mean of six numbers is 14. Five of them total 61. Find the sixth number.',
    marks: 3,
    answer: '23',
    solution: ['Total $84$. Sixth number $84-61=23$.'],
  }),
  numeric({
    id: 'gcse3-11',
    skill: 'Indices',
    ao: 1,
    chapter: 7,
    prompt: 'Work out $2^6 \\div 2^2$.',
    marks: 2,
    answer: '16',
    accepted: ['2^4'],
    solution: ['$2^{6-2} = 2^4 = 16$.'],
  }),
  numeric({
    id: 'gcse3-12',
    skill: 'Inequalities',
    ao: 1,
    chapter: 13,
    prompt: 'List the integers that satisfy $-4 \\le n < 1$. Write them in order, separated by commas.',
    marks: 2,
    answer: '-4,-3,-2,-1,0',
    accepted: ['-4, -3, -2, -1, 0'],
    solution: ['Integers from $-4$ up to but not including 1.'],
  }),
  numeric({
    id: 'gcse3-13',
    skill: 'Enlargement',
    ao: 2,
    chapter: 26,
    prompt:
      'A rectangle $5\\,\\text{cm}$ by $3\\,\\text{cm}$ is enlarged by scale factor $\\dfrac{5}{2}$. Find the perimeter of the image, in centimetres.',
    marks: 3,
    answer: '40',
    solution: ['New sides $12.5$ and $7.5$. Perimeter $2(12.5+7.5)=40$.'],
  }),
  numeric({
    id: 'gcse3-17',
    skill: 'Fractions',
    ao: 1,
    chapter: 4,
    prompt: 'Work out $\\dfrac{2}{3} + \\dfrac{1}{6}$.',
    marks: 2,
    answer: '5/6',
    solution: ['$\\dfrac{4}{6} + \\dfrac{1}{6} = \\dfrac{5}{6}$.'],
  }),
  numeric({
    id: 'gcse3-18',
    skill: 'Directed numbers',
    ao: 1,
    chapter: 2,
    prompt: 'Work out $-9 + 14 - 8$.',
    marks: 2,
    answer: '-3',
    solution: ['$-9+14=5$, then $5-8=-3$.'],
  }),
  numeric({
    id: 'gcse3-19',
    skill: 'Angles',
    ao: 2,
    chapter: 21,
    prompt: 'A triangle has angles $48^\\circ$, $61^\\circ$ and $z$. Find $z$.',
    marks: 2,
    answer: '71',
    solution: ['$z = 180 - 109 = 71$.'],
  }),
  numeric({
    id: 'gcse3-20',
    skill: 'Rounding',
    ao: 1,
    chapter: 1,
    prompt: 'Round $3.1416$ to 2 decimal places.',
    marks: 1,
    answer: '3.14',
    solution: ['The third decimal digit is 1, so it rounds down to 3.14.'],
  }),
  numeric({
    id: 'gcse3-21',
    skill: 'Percentages',
    ao: 2,
    chapter: 5,
    prompt: 'Increase 70 by $10\\%$.',
    marks: 2,
    answer: '77',
    solution: ['$10\\%$ of 70 is 7, so $70+7=77$.'],
  }),
  numeric({
    id: 'gcse3-14',
    skill: 'Simultaneous',
    ao: 3,
    chapter: 16,
    tier: 'H',
    prompt:
      'Adult tickets cost £$a$ and child tickets cost £$c$. 2 adults and 3 children cost £29. 4 adults and 1 child cost £33. Find the cost of one child ticket, in pounds.',
    marks: 4,
    answer: '5',
    solution: [
      '$2a+3c=29$ and $4a+c=33$.',
      'Double the first: $4a+6c=58$. Subtract the second: $5c=25$, so $c=5$.',
    ],
  }),
  numeric({
    id: 'gcse3-15',
    skill: 'Standard form',
    ao: 2,
    chapter: 8,
    tier: 'H',
    prompt: 'A sheet of paper is $8 \\times 10^{-5}\\,\\text{m}$ thick. How many sheets make a pile $2\\,\\text{cm}$ high?',
    marks: 3,
    answer: '250',
    solution: ['$2\\,\\text{cm} = 0.02\\,\\text{m} = 2 \\times 10^{-2}$. Number $= \\dfrac{2\\times 10^{-2}}{8\\times 10^{-5}} = 0.25 \\times 10^{3} = 250$.'],
  }),
  numeric({
    id: 'gcse3-16',
    skill: 'Graphs',
    ao: 3,
    chapter: 15,
    tier: 'H',
    prompt: 'Find the gradient of the line $4y - 2x = 12$.',
    marks: 2,
    answer: '0.5',
    accepted: ['1/2'],
    solution: ['$4y=2x+12$, so $y=\\dfrac{1}{2}x+3$. Gradient $\\dfrac{1}{2}$.'],
  }),
]

export const fullGcseExam: ExamMock = {
  id: 'full-gcse',
  title: 'Full GCSE mock',
  subtitle: 'Entire spec · three papers · AQA/Edexcel shape',
  focus:
    'Three 90-minute papers on the full practice-book specification, filtered to your Foundation or Higher tier. Paper 1 is non-calculator; Papers 2 and 3 allow a calculator. Original questions only — not a past paper.',
  stage: 'full',
  papers: [
    { id: 'paper-1', title: 'Paper 1', calculator: 'non-calc', durationMinutes: 90, questions: paper1 },
    { id: 'paper-2', title: 'Paper 2', calculator: 'calc', durationMinutes: 90, questions: paper2 },
    { id: 'paper-3', title: 'Paper 3', calculator: 'calc', durationMinutes: 90, questions: paper3 },
  ],
}
