import { multi, numeric } from '../make'
import type { ExamMock } from '../../lib/types'

const paper1 = [
  multi({
    id: 'mar1-1',
    skill: 'Number',
    ao: 1,
    chapter: 3,
    prompt: 'This question is about factors and directed numbers.',
    parts: [
      {
        id: 'mar1-1a',
        label: 'a',
        prompt: 'Write 84 as a product of prime factors, such as $2^2 \\times 3 \\times 7$.',
        marks: 2,
        answer: '2^2 x 3 x 7',
        accepted: ['2^2*3*7', '2^2 × 3 × 7', '2 x 2 x 3 x 7'],
        placeholder: 'e.g. 2^2 x 3 x 7',
        solution: ['$84 = 2^2 \\times 3 \\times 7$.'],
      },
      {
        id: 'mar1-1b',
        label: 'b',
        prompt: 'Work out $(-3)^3 - 4 \\times -5$.',
        marks: 2,
        answer: '-7',
        solution: ['$(-3)^3 = -27$ and $4 \\times -5 = -20$. Then $-27 - (-20) = -7$.'],
      },
    ],
  }),
  multi({
    id: 'mar1-2',
    skill: 'Fractions',
    ao: 1,
    chapter: 4,
    prompt: 'Calculate with fractions.',
    parts: [
      {
        id: 'mar1-2a',
        label: 'a',
        prompt: 'Work out $3\\dfrac{1}{4} - 1\\dfrac{5}{6}$.',
        marks: 3,
        answer: '17/12',
        accepted: ['1 5/12'],
        solution: ['$\\dfrac{13}{4} - \\dfrac{11}{6} = \\dfrac{39}{12} - \\dfrac{22}{12} = \\dfrac{17}{12}$.'],
      },
      {
        id: 'mar1-2b',
        label: 'b',
        prompt: 'Work out $\\dfrac{5}{8} \\div 2\\dfrac{1}{2}$.',
        marks: 2,
        answer: '1/4',
        solution: ['$\\dfrac{5}{8} \\div \\dfrac{5}{2} = \\dfrac{5}{8} \\times \\dfrac{2}{5} = \\dfrac{1}{4}$.'],
      },
    ],
  }),
  numeric({
    id: 'mar1-3',
    skill: 'Percentages',
    ao: 2,
    chapter: 5,
    prompt: 'Increase 240 by $17.5\\%$.',
    marks: 3,
    answer: '282',
    solution: ['$10\\% = 24$, $5\\% = 12$, $2.5\\% = 6$. Increase $42$. New value $282$.'],
  }),
  multi({
    id: 'mar1-4',
    skill: 'Algebra',
    ao: 1,
    chapter: 10,
    prompt: 'Expand and factorise.',
    parts: [
      {
        id: 'mar1-4a',
        label: 'a',
        prompt: 'Expand $(x+4)(x-7)$.',
        marks: 2,
        answer: 'x^2-3x-28',
        accepted: ['x^2 - 3x - 28'],
        solution: ['$x^2 - 7x + 4x - 28 = x^2 - 3x - 28$.'],
      },
      {
        id: 'mar1-4b',
        label: 'b',
        prompt: 'Factorise $6x^2 - 9x$.',
        marks: 2,
        answer: '3x(2x-3)',
        accepted: ['3x(2x - 3)'],
        solution: ['Common factor $3x$: $3x(2x-3)$.'],
      },
    ],
  }),
  numeric({
    id: 'mar1-5',
    skill: 'Linear equations',
    ao: 1,
    chapter: 11,
    prompt: 'Solve $\\dfrac{2x+1}{3} + \\dfrac{x}{2} = 5$.',
    marks: 4,
    answer: '4',
    solution: [
      'Multiply through by 6: $2(2x+1) + 3x = 30$.',
      '$4x + 2 + 3x = 30$, so $7x = 28$ and $x = 4$.',
    ],
  }),
  multi({
    id: 'mar1-6',
    skill: 'Ratio',
    ao: 2,
    chapter: 17,
    prompt: 'Sugar is mixed with flour in the ratio $2 : 7$. A baker uses $350\\,\\text{g}$ of flour.',
    parts: [
      {
        id: 'mar1-6a',
        label: 'a',
        prompt: 'How many grams of sugar are used?',
        marks: 2,
        answer: '100',
        solution: ['Sugar $= \\dfrac{2}{7} \\times 350 = 100$ g.'],
      },
      {
        id: 'mar1-6b',
        label: 'b',
        prompt: 'The baker then adds $50\\,\\text{g}$ more sugar. Write the new sugar : flour ratio in its simplest form.',
        marks: 2,
        answer: '3:7',
        accepted: ['3 : 7'],
        solution: ['Sugar is now $150\\,\\text{g}$. $150:350 = 3:7$.'],
      },
    ],
  }),
  numeric({
    id: 'mar1-7',
    skill: 'Angles',
    ao: 2,
    chapter: 21,
    prompt: 'In a triangle, two angles are $2x$ and $3x$. The third angle is $80^\\circ$. Find $x$.',
    marks: 3,
    answer: '20',
    solution: ['$2x+3x+80=180$, so $5x=100$ and $x=20$.'],
  }),
  numeric({
    id: 'mar1-8',
    skill: 'Pythagoras',
    ao: 2,
    chapter: 24,
    prompt:
      'A right-angled triangle has hypotenuse $26\\,\\text{cm}$ and one side $10\\,\\text{cm}$. Find the other side, in centimetres.',
    marks: 3,
    answer: '24',
    solution: ['$26^2 - 10^2 = 676 - 100 = 576$. Side $= \\sqrt{576} = 24$.'],
  }),
  numeric({
    id: 'mar1-9',
    skill: 'Probability',
    ao: 2,
    chapter: 28,
    prompt:
      'A card is taken from a 52-card pack. What is the probability it is a heart or an ace? Give your answer as a fraction in its lowest terms.',
    marks: 3,
    answer: '4/13',
    accepted: ['16/52'],
    solution: [
      '13 hearts and 4 aces, but the ace of hearts is counted twice, so $13+4-1=16$ cards.',
      '$\\dfrac{16}{52} = \\dfrac{4}{13}$.',
    ],
  }),
  multi({
    id: 'mar1-10',
    skill: 'Averages',
    ao: 3,
    chapter: 30,
    prompt: 'The numbers $4, 9, x, 11, 16$ are listed in increasing order and have a median of 10.',
    parts: [
      {
        id: 'mar1-10a',
        label: 'a',
        prompt: 'Find $x$.',
        marks: 1,
        answer: '10',
        solution: ['The middle value is $x$, so $x=10$.'],
      },
      {
        id: 'mar1-10b',
        label: 'b',
        prompt: 'Find the mean of the five numbers.',
        marks: 2,
        answer: '10',
        solution: ['Sum $4+9+10+11+16=50$. Mean $10$.'],
      },
    ],
  }),
  numeric({
    id: 'mar1-11',
    skill: 'Area',
    ao: 3,
    chapter: 23,
    prompt: 'A triangle has base $14\\,\\text{cm}$ and perpendicular height $9\\,\\text{cm}$. Find its area in cm$^2$.',
    marks: 2,
    answer: '63',
    solution: ['Area $= \\dfrac{1}{2} \\times 14 \\times 9 = 63$.'],
  }),
  numeric({
    id: 'mar1-12',
    skill: 'Sequences',
    ao: 2,
    chapter: 14,
    prompt: 'The $n$th term of a sequence is $n^2 - 3$. Find the 8th term.',
    marks: 2,
    answer: '61',
    solution: ['$8^2 - 3 = 64 - 3 = 61$.'],
  }),
  numeric({
    id: 'mar1-13',
    skill: 'Standard form',
    ao: 1,
    chapter: 8,
    prompt: 'Write $7.2 \\times 10^5$ as an ordinary number.',
    marks: 2,
    answer: '720000',
    accepted: ['720,000'],
    solution: ['Move the point 5 places: $720\\,000$.'],
  }),
  numeric({
    id: 'mar1-14',
    skill: 'Inequalities',
    ao: 1,
    chapter: 13,
    prompt:
      'Solve $5 - 3x < 14$. Give the critical value that $x$ is greater than. Reverse the inequality when dividing by a negative.',
    marks: 3,
    answer: '-3',
    solution: ['$-3x < 9$. Divide by $-3$ and reverse: $x > -3$.'],
  }),
  numeric({
    id: 'mar1-15',
    skill: 'Proportion',
    ao: 3,
    chapter: 18,
    prompt: '12 workers finish a job in 15 days. How many days would 20 workers take, at the same rate?',
    marks: 3,
    answer: '9',
    solution: ['Total worker-days $= 12 \\times 15 = 180$. Twenty workers take $180 \\div 20 = 9$ days.'],
  }),
  numeric({
    id: 'mar1-16',
    skill: 'Perimeter',
    ao: 3,
    chapter: 23,
    prompt:
      'A rectangle is $3x+2$ long and $x-1$ wide. Its perimeter is $50$. Find $x$.',
    marks: 3,
    answer: '6',
    solution: ['$2(3x+2+x-1)=50$, so $2(4x+1)=50$, $4x+1=25$, $4x=24$, $x=6$.'],
  }),
  numeric({
    id: 'mar1-20',
    skill: 'Decimals',
    ao: 1,
    chapter: 6,
    prompt: 'Work out $0.6 + 0.75$.',
    marks: 1,
    answer: '1.35',
    solution: ['$0.60 + 0.75 = 1.35$.'],
  }),
  numeric({
    id: 'mar1-21',
    skill: 'Expressions',
    ao: 1,
    chapter: 9,
    prompt: 'Simplify $4(2x+3) - x$.',
    marks: 2,
    answer: '7x+12',
    accepted: ['7x + 12'],
    solution: ['$8x+12-x=7x+12$.'],
  }),
  numeric({
    id: 'mar1-22',
    skill: 'HCF',
    ao: 1,
    chapter: 3,
    prompt: 'Find the HCF of 42 and 70.',
    marks: 2,
    answer: '14',
    solution: ['$42=2\\times 3\\times 7$ and $70=2\\times 5\\times 7$. HCF $=14$.'],
  }),
  numeric({
    id: 'mar1-23',
    skill: 'FDP',
    ao: 1,
    chapter: 6,
    prompt: 'Write $0.2$ as a fraction in its lowest terms.',
    marks: 1,
    answer: '1/5',
    solution: ['$0.2 = \\dfrac{1}{5}$.'],
  }),
  numeric({
    id: 'mar1-24',
    skill: 'Percentages',
    ao: 2,
    chapter: 5,
    prompt: 'Work out $40\\%$ of 55.',
    marks: 2,
    answer: '22',
    solution: ['$10\\% = 5.5$, so $40\\% = 22$.'],
  }),
  multi({
    id: 'mar1-17',
    skill: 'Simultaneous',
    ao: 2,
    chapter: 16,
    tier: 'H',
    prompt: 'Solve $4x - y = 11$ and $x + y = 4$.',
    parts: [
      {
        id: 'mar1-17a',
        label: 'a',
        prompt: 'Find $x$.',
        marks: 2,
        answer: '3',
        solution: ['Add: $5x = 15$, so $x = 3$.'],
      },
      {
        id: 'mar1-17b',
        label: 'b',
        prompt: 'Find $y$.',
        marks: 2,
        answer: '1',
        solution: ['$3 + y = 4$, so $y = 1$.'],
      },
    ],
  }),
  numeric({
    id: 'mar1-18',
    skill: 'Indices',
    ao: 1,
    chapter: 7,
    tier: 'H',
    prompt: 'Simplify $(2^3)^2 \\times 2^{-1}$. Give your answer as a power of 2.',
    marks: 2,
    answer: '2^5',
    accepted: ['32'],
    placeholder: 'e.g. 2^5',
    solution: ['$(2^3)^2 = 2^6$, then $2^6 \\times 2^{-1} = 2^5$.'],
  }),
  numeric({
    id: 'mar1-19',
    skill: 'Graphs',
    ao: 3,
    chapter: 15,
    tier: 'H',
    prompt: 'Find the $y$-intercept of the line through $(2, 11)$ with gradient 3.',
    marks: 3,
    answer: '5',
    solution: ['$y-11=3(x-2)$, so $y=3x+5$. The intercept is 5.'],
  }),
]

const paper2 = [
  numeric({
    id: 'mar2-1',
    skill: 'Reverse percentages',
    ao: 2,
    chapter: 5,
    prompt: 'After a $12\\%$ increase, a salary is £22,400. What was the salary before the increase, in pounds?',
    marks: 3,
    answer: '20000',
    accepted: ['20,000'],
    solution: ['£22,400 is $112\\%$. $22400 \\div 1.12 = 20000$.'],
  }),
  numeric({
    id: 'mar2-2',
    skill: 'Compound interest',
    ao: 2,
    chapter: 5,
    prompt:
      '£850 is invested at $2.5\\%$ compound interest for 2 years. Find the value after 2 years, in pounds, to the nearest penny.',
    marks: 3,
    answer: '893.03',
    tolerance: 0.02,
    solution: ['$850 \\times 1.025^2 = 850 \\times 1.050625 = 893.03$.'],
  }),
  multi({
    id: 'mar2-3',
    skill: 'Trigonometry',
    ao: 2,
    chapter: 25,
    prompt: 'In right-angled triangle $PQR$, $\\angle R = 90^\\circ$, $PR = 9\\,\\text{cm}$ and $\\angle P = 34^\\circ$.',
    parts: [
      {
        id: 'mar2-3a',
        label: 'a',
        prompt: 'Find $QR$, in centimetres, to 1 decimal place.',
        marks: 3,
        answer: '6.1',
        tolerance: 0.15,
        solution: [
          '$QR$ is opposite $P$. $\\tan 34^\\circ = \\dfrac{QR}{9}$, so $QR = 9\\tan 34^\\circ \\approx 6.07$, which is $6.1$ to 1 d.p.',
        ],
      },
      {
        id: 'mar2-3b',
        label: 'b',
        prompt: 'Find $PQ$, in centimetres, to 1 decimal place.',
        marks: 2,
        answer: '10.9',
        tolerance: 0.15,
        solution: [
          '$\\cos 34^\\circ = \\dfrac{9}{PQ}$, so $PQ = \\dfrac{9}{\\cos 34^\\circ} \\approx 10.85$, which is $10.9$ to 1 d.p.',
        ],
      },
    ],
  }),
  multi({
    id: 'mar2-4',
    skill: 'Circles',
    ao: 2,
    chapter: 27,
    prompt: 'A circle has diameter $18\\,\\text{cm}$.',
    parts: [
      {
        id: 'mar2-4a',
        label: 'a',
        prompt: 'Find the circumference, to 1 decimal place.',
        marks: 2,
        answer: '56.5',
        tolerance: 0.2,
        solution: ['$C = 18\\pi \\approx 56.55$, so $56.5$ to 1 d.p.'],
      },
      {
        id: 'mar2-4b',
        label: 'b',
        prompt: 'Find the area, to the nearest whole number.',
        marks: 2,
        answer: '254',
        accepted: ['255'],
        tolerance: 1,
        solution: ['Radius 9. $A = 81\\pi \\approx 254.5$, so $254$ or $255$ to the nearest integer.'],
      },
    ],
  }),
  numeric({
    id: 'mar2-5',
    skill: 'Speed',
    ao: 2,
    chapter: 19,
    prompt: 'A runner covers $5\\,\\text{km}$ in 22 minutes. Find the average speed in km/h, to 1 decimal place.',
    marks: 3,
    answer: '13.6',
    tolerance: 0.15,
    solution: [
      '22 minutes $= \\dfrac{22}{60}$ hours. Speed $= 5 \\times \\dfrac{60}{22} \\approx 13.64$, so $13.6$ km/h.',
    ],
  }),
  multi({
    id: 'mar2-6',
    skill: 'Averages',
    ao: 2,
    chapter: 30,
    prompt: 'Frequency of scores: 1 (4 people), 2 (7 people), 3 (5 people), 4 (4 people).',
    parts: [
      {
        id: 'mar2-6a',
        label: 'a',
        prompt: 'Find the modal score.',
        marks: 1,
        answer: '2',
        solution: ['Score 2 has the highest frequency, 7.'],
      },
      {
        id: 'mar2-6b',
        label: 'b',
        prompt: 'Find the mean score.',
        marks: 3,
        answer: '2.45',
        accepted: ['49/20'],
        tolerance: 0.05,
        solution: ['Total people $20$. Total score $4+14+15+16=49$. Mean $49 \\div 20 = 2.45$.'],
      },
    ],
  }),
  numeric({
    id: 'mar2-7',
    skill: 'Density',
    ao: 3,
    chapter: 19,
    prompt: 'A wooden beam has density $0.65\\,\\text{g/cm}^3$ and mass $1.3\\,\\text{kg}$. Find its volume in cm$^3$.',
    marks: 3,
    answer: '2000',
    solution: ['$1.3\\,\\text{kg} = 1300\\,\\text{g}$. Volume $= 1300 \\div 0.65 = 2000$.'],
  }),
  numeric({
    id: 'mar2-8',
    skill: 'Volume',
    ao: 2,
    chapter: 27,
    prompt: 'A cylinder has radius $4\\,\\text{cm}$ and height $10\\,\\text{cm}$. Find its volume, to the nearest whole number.',
    marks: 3,
    answer: '503',
    tolerance: 2,
    solution: ['$V = \\pi r^2 h = 160\\pi \\approx 502.7$, so $503$.'],
  }),
  numeric({
    id: 'mar2-9',
    skill: 'Scale',
    ao: 2,
    chapter: 20,
    prompt: 'On a map, $3.5\\,\\text{cm}$ represents $14\\,\\text{km}$. What distance, in kilometres, does $6.3\\,\\text{cm}$ represent?',
    marks: 3,
    answer: '25.2',
    solution: ['$1\\,\\text{cm}$ represents $4\\,\\text{km}$. $6.3 \\times 4 = 25.2$ km.'],
  }),
  numeric({
    id: 'mar2-10',
    skill: 'Formulae',
    ao: 1,
    chapter: 12,
    prompt: 'The formula $s = \\dfrac{1}{2}(u+v)t$ is used for motion. Find $s$ when $u=6$, $v=14$ and $t=5$.',
    marks: 2,
    answer: '50',
    solution: ['$s = \\dfrac{1}{2}(6+14)\\times 5 = 10 \\times 5 = 50$.'],
  }),
  numeric({
    id: 'mar2-11',
    skill: 'Transformations',
    ao: 1,
    chapter: 26,
    prompt: 'Point $(3, -2)$ is reflected in the $x$-axis. Write the image coordinates as (x,y).',
    marks: 2,
    answer: '(3,2)',
    accepted: ['(3, 2)', '3,2'],
    solution: ['Reflection in the $x$-axis sends $(x,y)$ to $(x,-y)$, so $(3,-2)$ maps to $(3,2)$.'],
  }),
  numeric({
    id: 'mar2-12',
    skill: 'FDP',
    ao: 1,
    chapter: 6,
    prompt: 'Write $0.16$ as a fraction in its lowest terms.',
    marks: 2,
    answer: '4/25',
    solution: ['$0.16 = \\dfrac{16}{100} = \\dfrac{4}{25}$.'],
  }),
  numeric({
    id: 'mar2-13',
    skill: 'Probability',
    ao: 3,
    chapter: 29,
    prompt:
      'A bag holds 4 red and 6 blue counters. Two counters are taken at random without replacement. Find the probability both are red, as a fraction.',
    marks: 3,
    answer: '2/15',
    accepted: ['12/90'],
    solution: ['$\\dfrac{4}{10} \\times \\dfrac{3}{9} = \\dfrac{12}{90} = \\dfrac{2}{15}$.'],
  }),
  numeric({
    id: 'mar2-14',
    skill: 'Area problem',
    ao: 3,
    chapter: 23,
    prompt:
      'A rectangular patio is $7.2\\,\\text{m}$ by $4.5\\,\\text{m}$. Tiles cover $0.4\\,\\text{m}^2$ each and cost £3.50. How much does it cost, in pounds, to tile the patio?',
    marks: 4,
    answer: '283.5',
    accepted: ['283.50'],
    tolerance: 0.05,
    solution: ['Area $32.4\\,\\text{m}^2$. Tiles needed $32.4 \\div 0.4 = 81$. Cost $81 \\times 3.50 = 283.50$.'],
  }),
  numeric({
    id: 'mar2-18',
    skill: 'Percentages',
    ao: 1,
    chapter: 5,
    prompt: 'Work out $12\\%$ of 250.',
    marks: 2,
    answer: '30',
    solution: ['$10\\% = 25$ and $2\\% = 5$, so $12\\% = 30$.'],
  }),
  numeric({
    id: 'mar2-19',
    skill: 'Ratio',
    ao: 2,
    chapter: 17,
    prompt: 'Share 96 in the ratio $1 : 3 : 4$. What is the middle share?',
    marks: 2,
    answer: '36',
    solution: ['Parts total 8. Middle share $3 \\times 12 = 36$.'],
  }),
  numeric({
    id: 'mar2-20',
    skill: 'Linear equations',
    ao: 1,
    chapter: 11,
    prompt: 'Solve $8x + 3 = 35$.',
    marks: 2,
    answer: '4',
    solution: ['$8x = 32$, so $x = 4$.'],
  }),
  numeric({
    id: 'mar2-21',
    skill: 'Decimals',
    ao: 1,
    chapter: 6,
    prompt: 'Work out $9.6 - 3.75$.',
    marks: 2,
    answer: '5.85',
    solution: ['$9.60 - 3.75 = 5.85$.'],
  }),
  numeric({
    id: 'mar2-15',
    skill: 'Standard form',
    ao: 1,
    chapter: 8,
    tier: 'H',
    prompt: 'Work out $(3.6 \\times 10^{-3}) \\times (5 \\times 10^8)$. Give your answer in standard form.',
    marks: 3,
    answer: '1.8 x 10^6',
    accepted: ['1.8×10^6', '1.8e6', '1800000'],
    placeholder: 'e.g. 1.8 x 10^6',
    solution: ['$3.6 \\times 5 = 18$ and $10^{-3+8}=10^5$, so $18 \\times 10^5 = 1.8 \\times 10^6$.'],
  }),
  numeric({
    id: 'mar2-16',
    skill: 'Rearranging',
    ao: 2,
    chapter: 12,
    tier: 'H',
    prompt: 'Make $t$ the subject of $v = u + at$. Write an expression such as (v-u)/a.',
    marks: 2,
    answer: '(v-u)/a',
    accepted: ['(v - u)/a'],
    placeholder: 'e.g. (v-u)/a',
    solution: ['$v-u=at$, so $t=\\dfrac{v-u}{a}$.'],
  }),
  numeric({
    id: 'mar2-17',
    skill: 'Trigonometry',
    ao: 3,
    chapter: 25,
    tier: 'H',
    prompt:
      'A cliff is $48\\,\\text{m}$ high. The angle of depression from the top to a boat is $21^\\circ$. How far is the boat from the base of the cliff, in metres, to the nearest metre?',
    marks: 3,
    answer: '125',
    tolerance: 2,
    solution: ['$\\tan 21^\\circ = \\dfrac{48}{d}$, so $d = \\dfrac{48}{\\tan 21^\\circ} \\approx 124.8$, which is $125$ m.'],
  }),
]

const paper3 = [
  multi({
    id: 'mar3-1',
    skill: 'Percentages',
    ao: 3,
    chapter: 5,
    prompt: 'A town had 12 000 people. The population rose by $8\\%$ in 2023 and then fell by $5\\%$ in 2024.',
    parts: [
      {
        id: 'mar3-1a',
        label: 'a',
        prompt: 'Find the 2023 population.',
        marks: 2,
        answer: '12960',
        accepted: ['12,960'],
        solution: ['$12000 \\times 1.08 = 12960$.'],
      },
      {
        id: 'mar3-1b',
        label: 'b',
        prompt: 'Find the 2024 population.',
        marks: 2,
        answer: '12312',
        accepted: ['12,312'],
        solution: ['$12960 \\times 0.95 = 12312$.'],
      },
    ],
  }),
  numeric({
    id: 'mar3-2',
    skill: 'Ratio',
    ao: 3,
    chapter: 17,
    prompt:
      'Three sisters share £270 in the ratio $4 : 5 : 9$. The eldest then gives £18 to the youngest. How much does the youngest have then, in pounds?',
    marks: 4,
    answer: '78',
    solution: [
      'Parts $18$. One part $£15$. Youngest first has $4 \\times 15 = 60$.',
      'After the gift, $60 + 18 = 78$.',
    ],
  }),
  multi({
    id: 'mar3-3',
    skill: 'Algebra',
    ao: 1,
    chapter: 11,
    prompt: 'Solve these equations.',
    parts: [
      {
        id: 'mar3-3a',
        label: 'a',
        prompt: 'Solve $4(2x-1) = 3x + 17$.',
        marks: 3,
        answer: '4.2',
        accepted: ['21/5', '4 1/5'],
        solution: ['$8x-4=3x+17$, so $5x=21$ and $x=\\dfrac{21}{5}$.'],
      },
      {
        id: 'mar3-3b',
        label: 'b',
        prompt: 'Solve $\\dfrac{x}{5} = 3$.',
        marks: 1,
        answer: '15',
        solution: ['$x = 15$.'],
      },
    ],
  }),
  numeric({
    id: 'mar3-4',
    skill: 'Pythagoras',
    ao: 3,
    chapter: 24,
    prompt:
      'A guy rope is $13\\,\\text{m}$ long and is fixed $5\\,\\text{m}$ from the base of a vertical mast. How tall is the mast, in metres?',
    marks: 3,
    answer: '12',
    solution: ['$13^2 - 5^2 = 169 - 25 = 144$. Height $= 12$.'],
  }),
  multi({
    id: 'mar3-5',
    skill: 'Tree diagrams',
    ao: 3,
    chapter: 29,
    prompt:
      'A box has 5 good bulbs and 2 faulty bulbs. Two bulbs are taken at random without replacement.',
    parts: [
      {
        id: 'mar3-5a',
        label: 'a',
        prompt: 'Find the probability both are good, as a fraction.',
        marks: 2,
        answer: '10/21',
        accepted: ['20/42'],
        solution: ['$\\dfrac{5}{7} \\times \\dfrac{4}{6} = \\dfrac{20}{42} = \\dfrac{10}{21}$.'],
      },
      {
        id: 'mar3-5b',
        label: 'b',
        prompt: 'Find the probability that exactly one is faulty, as a fraction.',
        marks: 3,
        answer: '10/21',
        accepted: ['20/42'],
        solution: [
          'Good then faulty: $\\dfrac{5}{7}\\times\\dfrac{2}{6}=\\dfrac{10}{42}$.',
          'Faulty then good: $\\dfrac{2}{7}\\times\\dfrac{5}{6}=\\dfrac{10}{42}$.',
          'Total $\\dfrac{20}{42} = \\dfrac{10}{21}$.',
        ],
      },
    ],
  }),
  numeric({
    id: 'mar3-6',
    skill: 'Circles',
    ao: 3,
    chapter: 27,
    prompt:
      'A circular pizza has radius $12\\,\\text{cm}$. It is cut into 8 equal slices. Find the area of one slice, to the nearest whole number.',
    marks: 3,
    answer: '57',
    tolerance: 1,
    solution: ['Full area $144\\pi \\approx 452.4$. One eighth $\\approx 56.5$, so $57$.'],
  }),
  numeric({
    id: 'mar3-7',
    skill: 'Compound measures',
    ao: 2,
    chapter: 19,
    prompt: 'A car travels for 40 minutes at $72\\,\\text{km/h}$. How many kilometres does it travel?',
    marks: 2,
    answer: '48',
    solution: ['40 minutes $= \\dfrac{2}{3}$ hour. Distance $= 72 \\times \\dfrac{2}{3} = 48$ km.'],
  }),
  numeric({
    id: 'mar3-8',
    skill: 'Sequences',
    ao: 2,
    chapter: 14,
    prompt: 'A sequence is $7, 12, 17, 22, \\ldots$ Which term is the first greater than 100?',
    marks: 3,
    answer: '20',
    solution: ['$n$th term $5n+2$. $5n+2>100$, $5n>98$, $n>19.6$, so the 20th term.'],
  }),
  numeric({
    id: 'mar3-9',
    skill: 'Volume',
    ao: 2,
    chapter: 23,
    prompt:
      'A triangular prism has a right-angled cross-section with legs $6\\,\\text{cm}$ and $8\\,\\text{cm}$, and length $15\\,\\text{cm}$. Find the volume in cm$^3$.',
    marks: 3,
    answer: '360',
    solution: ['Triangle area $24$. Volume $24 \\times 15 = 360$.'],
  }),
  numeric({
    id: 'mar3-10',
    skill: 'Averages',
    ao: 2,
    chapter: 30,
    prompt: 'The mean of five numbers is 18. Four of them are 11, 16, 20 and 25. Find the fifth number.',
    marks: 3,
    answer: '18',
    solution: ['Total $90$. Fifth number $90-(11+16+20+25)=18$.'],
  }),
  numeric({
    id: 'mar3-11',
    skill: 'Indices',
    ao: 1,
    chapter: 7,
    prompt: 'Work out $\\sqrt{169} + 2^4$.',
    marks: 2,
    answer: '29',
    solution: ['$13 + 16 = 29$.'],
  }),
  numeric({
    id: 'mar3-12',
    skill: 'Inequalities',
    ao: 1,
    chapter: 13,
    prompt: 'List the integers that satisfy $1 \\le 2n < 9$. Write them in order, separated by commas.',
    marks: 2,
    answer: '1,2,3,4',
    accepted: ['1, 2, 3, 4'],
    solution: ['$1 \\le 2n < 9$, so $0.5 \\le n < 4.5$. Integers $1,2,3,4$.'],
  }),
  numeric({
    id: 'mar3-13',
    skill: 'Enlargement',
    ao: 2,
    chapter: 26,
    prompt: 'A triangle of area $18\\,\\text{cm}^2$ is enlarged by scale factor 3. Find the area of the image, in cm$^2$.',
    marks: 3,
    answer: '162',
    solution: ['Area scale factor $3^2 = 9$. New area $18 \\times 9 = 162$.'],
  }),
  numeric({
    id: 'mar3-17',
    skill: 'Fractions',
    ao: 1,
    chapter: 4,
    prompt: 'Work out $\\dfrac{7}{10} - \\dfrac{1}{5}$.',
    marks: 2,
    answer: '1/2',
    accepted: ['0.5'],
    solution: ['$\\dfrac{7}{10} - \\dfrac{2}{10} = \\dfrac{5}{10} = \\dfrac{1}{2}$.'],
  }),
  numeric({
    id: 'mar3-18',
    skill: 'Directed numbers',
    ao: 1,
    chapter: 2,
    prompt: 'Work out $9 - 15 + -2$.',
    marks: 2,
    answer: '-8',
    solution: ['$9-15=-6$, then $-6 + -2 = -8$.'],
  }),
  numeric({
    id: 'mar3-19',
    skill: 'Angles',
    ao: 2,
    chapter: 21,
    prompt: 'Angles in a quadrilateral are $80^\\circ$, $95^\\circ$, $110^\\circ$ and $y$. Find $y$.',
    marks: 2,
    answer: '75',
    solution: ['Sum of interior angles $360$. $y = 360 - 285 = 75$.'],
  }),
  numeric({
    id: 'mar3-20',
    skill: 'Rounding',
    ao: 1,
    chapter: 1,
    prompt: 'Round $2485$ to the nearest 100.',
    marks: 1,
    answer: '2500',
    accepted: ['2,500'],
    solution: ['The tens digit is 8, so 2485 rounds up to 2500.'],
  }),
  numeric({
    id: 'mar3-21',
    skill: 'Percentages',
    ao: 2,
    chapter: 5,
    prompt: 'Increase 45 by $20\\%$.',
    marks: 2,
    answer: '54',
    solution: ['$20\\%$ of 45 is 9, so $45+9=54$.'],
  }),
  numeric({
    id: 'mar3-14',
    skill: 'Simultaneous',
    ao: 3,
    chapter: 16,
    tier: 'H',
    prompt:
      'Pens cost £$p$ and pencils cost £$q$. 2 pens and 3 pencils cost £2.10. 4 pens and 1 pencil cost £2.70. Find the cost of one pen, in pounds.',
    marks: 4,
    answer: '0.6',
    accepted: ['0.60', '3/5'],
    tolerance: 0.01,
    solution: [
      '$2p+3q=2.10$ and $4p+q=2.70$.',
      'Double the first: $4p+6q=4.20$. Subtract the second: $5q=1.50$, so $q=0.30$.',
      'Then $4p+0.30=2.70$, $4p=2.40$, $p=0.60$.',
    ],
  }),
  numeric({
    id: 'mar3-15',
    skill: 'Standard form',
    ao: 2,
    chapter: 8,
    tier: 'H',
    prompt: 'Light travels at about $3 \\times 10^8$ m/s. How far, in metres, in standard form, does it travel in $2 \\times 10^{-3}$ seconds?',
    marks: 3,
    answer: '6 x 10^5',
    accepted: ['6×10^5', '6e5', '600000'],
    placeholder: 'e.g. 6 x 10^5',
    solution: ['$(3 \\times 10^8)(2 \\times 10^{-3}) = 6 \\times 10^5$.'],
  }),
  numeric({
    id: 'mar3-16',
    skill: 'Graphs',
    ao: 3,
    chapter: 15,
    tier: 'H',
    prompt: 'The line $3x + 4y = 24$ meets the $x$-axis at $(a, 0)$. Find $a$.',
    marks: 2,
    answer: '8',
    solution: ['When $y=0$, $3x=24$, so $a=8$.'],
  }),
]

export const marchExam: ExamMock = {
  id: 'march',
  title: 'March mock',
  subtitle: 'Y11 spring · full spec',
  focus:
    'Three 90-minute papers covering the full 30-chapter practice-book spec. Paper 1 is non-calculator; Papers 2 and 3 allow a calculator. Original questions only.',
  stage: 'march',
  papers: [
    { id: 'paper-1', title: 'Paper 1', calculator: 'non-calc', durationMinutes: 90, questions: paper1 },
    { id: 'paper-2', title: 'Paper 2', calculator: 'calc', durationMinutes: 90, questions: paper2 },
    { id: 'paper-3', title: 'Paper 3', calculator: 'calc', durationMinutes: 90, questions: paper3 },
  ],
}
