import { mc, multi, numeric } from '../make'
import type { ExamMock } from '../../lib/types'

const paper1 = [
  multi({
    id: 'nov1-1',
    skill: 'Number',
    ao: 1,
    chapter: 1,
    prompt: 'This question is about integers and directed numbers.',
    parts: [
      {
        id: 'nov1-1a',
        label: 'a',
        prompt: 'Work out $7 - 3 \\times (8 - 11)$.',
        marks: 2,
        answer: '16',
        solution: ['Brackets first: $8-11=-3$. Then $3 \\times -3 = -9$. Then $7 - (-9) = 16$.'],
      },
      {
        id: 'nov1-1b',
        label: 'b',
        prompt: 'Find the LCM of 18 and 24.',
        marks: 2,
        answer: '72',
        solution: ['$18=2\\times 3^2$ and $24=2^3\\times 3$. LCM $= 2^3 \\times 3^2 = 72$.'],
      },
    ],
  }),
  multi({
    id: 'nov1-2',
    skill: 'Fractions',
    ao: 1,
    chapter: 4,
    prompt: 'Calculate with mixed numbers.',
    parts: [
      {
        id: 'nov1-2a',
        label: 'a',
        prompt: 'Work out $2\\dfrac{1}{5} + 1\\dfrac{2}{3}$.',
        marks: 3,
        answer: '58/15',
        accepted: ['3 13/15'],
        solution: ['$\\dfrac{11}{5} + \\dfrac{5}{3} = \\dfrac{33}{15} + \\dfrac{25}{15} = \\dfrac{58}{15}$.'],
      },
      {
        id: 'nov1-2b',
        label: 'b',
        prompt: 'Work out $1\\dfrac{1}{2} \\times \\dfrac{4}{9}$.',
        marks: 2,
        answer: '2/3',
        solution: ['$\\dfrac{3}{2} \\times \\dfrac{4}{9} = \\dfrac{12}{18} = \\dfrac{2}{3}$.'],
      },
    ],
  }),
  multi({
    id: 'nov1-3',
    skill: 'Percentages',
    ao: 2,
    chapter: 5,
    prompt: 'A jacket is priced at £85.',
    parts: [
      {
        id: 'nov1-3a',
        label: 'a',
        prompt: 'In a sale the price is reduced by $20\\%$. Find the sale price in pounds.',
        marks: 2,
        answer: '68',
        solution: ['$20\\%$ of 85 is 17, so $85-17=68$.'],
      },
      {
        id: 'nov1-3b',
        label: 'b',
        prompt: 'VAT of $20\\%$ is then added to the sale price. What is the final price in pounds?',
        marks: 2,
        answer: '81.6',
        accepted: ['81.60'],
        tolerance: 0.01,
        solution: ['$68 \\times 1.2 = 81.60$.'],
      },
    ],
  }),
  multi({
    id: 'nov1-4',
    skill: 'Algebra',
    ao: 1,
    chapter: 10,
    prompt: 'Expand and factorise.',
    parts: [
      {
        id: 'nov1-4a',
        label: 'a',
        prompt: 'Expand and simplify $4(2x-3) - 2(x+5)$.',
        marks: 3,
        answer: '6x-22',
        accepted: ['6x - 22'],
        solution: ['$8x-12-2x-10=6x-22$.'],
      },
      {
        id: 'nov1-4b',
        label: 'b',
        prompt: 'Factorise $x^2 + 7x + 10$.',
        marks: 2,
        answer: '(x+2)(x+5)',
        accepted: ['(x+5)(x+2)', '(x + 2)(x + 5)'],
        solution: ['Numbers that multiply to 10 and add to 7 are 2 and 5.'],
      },
    ],
  }),
  numeric({
    id: 'nov1-5',
    skill: 'Linear equations',
    ao: 1,
    chapter: 11,
    prompt: 'Solve $\\dfrac{3x-1}{4} = 5$.',
    marks: 3,
    answer: '7',
    solution: ['$3x-1=20$, so $3x=21$ and $x=7$.'],
  }),
  multi({
    id: 'nov1-6',
    skill: 'Ratio',
    ao: 2,
    chapter: 17,
    prompt: 'Blue and yellow paint are mixed in the ratio $3 : 5$ to make $4.8$ litres of green.',
    parts: [
      {
        id: 'nov1-6a',
        label: 'a',
        prompt: 'How many litres of blue paint are used?',
        marks: 2,
        answer: '1.8',
        accepted: ['9/5'],
        solution: ['Parts total 8. Blue $= \\dfrac{3}{8} \\times 4.8 = 1.8$ litres.'],
      },
      {
        id: 'nov1-6b',
        label: 'b',
        prompt: 'A second mix uses the same yellow amount but twice as much blue. Write the new blue : yellow ratio in its simplest form.',
        marks: 2,
        answer: '6:5',
        accepted: ['6 : 5'],
        solution: ['Blue doubles from 3 parts to 6 parts. Ratio $6:5$.'],
      },
    ],
  }),
  numeric({
    id: 'nov1-7',
    skill: 'Sequences',
    ao: 2,
    chapter: 14,
    prompt: 'The $n$th term of a sequence is $5n - 8$. Which term has value 47?',
    marks: 3,
    answer: '11',
    solution: ['$5n-8=47$, so $5n=55$ and $n=11$.'],
  }),
  multi({
    id: 'nov1-8',
    skill: 'Angles',
    ao: 2,
    chapter: 21,
    prompt: 'A regular hexagon has one exterior angle labelled $x$.',
    parts: [
      {
        id: 'nov1-8a',
        label: 'a',
        prompt: 'Work out $x$.',
        marks: 2,
        answer: '60',
        solution: ['Exterior angles of a regular $n$-gon are $360 \\div n$. $360 \\div 6 = 60$.'],
      },
      {
        id: 'nov1-8b',
        label: 'b',
        prompt: 'Work out an interior angle of the hexagon.',
        marks: 2,
        answer: '120',
        solution: ['Interior $= 180 - 60 = 120$.'],
      },
    ],
  }),
  numeric({
    id: 'nov1-9',
    skill: 'Pythagoras',
    ao: 2,
    chapter: 24,
    prompt:
      'A right-angled triangle has shorter sides $9\\,\\text{cm}$ and $12\\,\\text{cm}$. Find the hypotenuse in centimetres.',
    marks: 3,
    answer: '15',
    solution: ['$9^2 + 12^2 = 81 + 144 = 225$. Hypotenuse $= \\sqrt{225} = 15$.'],
  }),
  numeric({
    id: 'nov1-10',
    skill: 'Probability',
    ao: 2,
    chapter: 28,
    prompt:
      'A bag contains 5 red, 3 blue and 2 green counters. One counter is taken at random. What is the probability it is not blue? Give your answer as a fraction.',
    marks: 2,
    answer: '7/10',
    accepted: ['0.7'],
    solution: ['Total 10 counters. Not blue $= 7$. Probability $\\dfrac{7}{10}$.'],
  }),
  multi({
    id: 'nov1-11',
    skill: 'Averages',
    ao: 3,
    chapter: 30,
    prompt: 'Five test scores are $12, 15, 18, 18, 22$.',
    parts: [
      {
        id: 'nov1-11a',
        label: 'a',
        prompt: 'Find the median.',
        marks: 1,
        answer: '18',
        solution: ['The middle value of the ordered list is 18.'],
      },
      {
        id: 'nov1-11b',
        label: 'b',
        prompt: 'Find the mean.',
        marks: 2,
        answer: '17',
        solution: ['Sum $= 85$. Mean $= 85 \\div 5 = 17$.'],
      },
      {
        id: 'nov1-11c',
        label: 'c',
        prompt: 'A sixth score of 11 is included. Find the new mean.',
        marks: 2,
        answer: '16',
        solution: ['New sum $96$. Mean $96 \\div 6 = 16$.'],
      },
    ],
  }),
  numeric({
    id: 'nov1-12',
    skill: 'Area',
    ao: 3,
    chapter: 23,
    prompt:
      'A trapezium has parallel sides $9\\,\\text{cm}$ and $15\\,\\text{cm}$ and perpendicular height $6\\,\\text{cm}$. Find its area in cm$^2$.',
    marks: 3,
    answer: '72',
    solution: ['Area $= \\dfrac{1}{2}(9+15)\\times 6 = 12 \\times 6 = 72$.'],
  }),
  numeric({
    id: 'nov1-13',
    skill: 'Standard form',
    ao: 1,
    chapter: 8,
    prompt: 'Write $0.00036$ in standard form.',
    marks: 2,
    answer: '3.6 x 10^-4',
    accepted: ['3.6×10^-4', '3.6*10^-4', '3.6e-4'],
    placeholder: 'e.g. 3.6 x 10^-4',
    solution: ['$0.00036 = 3.6 \\times 10^{-4}$.'],
  }),
  numeric({
    id: 'nov1-14',
    skill: 'Proportion',
    ao: 3,
    chapter: 18,
    prompt: '8 identical notebooks cost £14. How much do 6 of the same notebooks cost, in pounds?',
    marks: 3,
    answer: '10.5',
    accepted: ['10.50'],
    tolerance: 0.01,
    solution: ['One notebook costs $14 \\div 8 = 1.75$. Six cost $1.75 \\times 6 = 10.50$.'],
  }),
  numeric({
    id: 'nov1-15',
    skill: 'Inequalities',
    ao: 1,
    chapter: 13,
    prompt: 'Solve $2x + 9 \\le 3$. Give the critical value that $x$ is less than or equal to.',
    marks: 3,
    answer: '-3',
    solution: ['$2x \\le -6$, so $x \\le -3$.'],
  }),
  numeric({
    id: 'nov1-19',
    skill: 'Decimals',
    ao: 1,
    chapter: 6,
    prompt: 'Work out $2.8 \\times 0.4$.',
    marks: 2,
    answer: '1.12',
    solution: ['$28 \\times 4 = 112$, then 2 decimal places: $1.12$.'],
  }),
  numeric({
    id: 'nov1-20',
    skill: 'Expressions',
    ao: 1,
    chapter: 9,
    prompt: 'Simplify $7a + 3b - 2a + 5b$.',
    marks: 2,
    answer: '5a+8b',
    accepted: ['5a + 8b'],
    solution: ['$7a-2a=5a$ and $3b+5b=8b$.'],
  }),
  numeric({
    id: 'nov1-21',
    skill: 'Substitution',
    ao: 1,
    chapter: 12,
    prompt: 'If $p = 3$ and $q = -2$, find the value of $4p - 3q$.',
    marks: 2,
    answer: '18',
    solution: ['$4\\times 3 - 3\\times(-2) = 12 + 6 = 18$.'],
  }),
  numeric({
    id: 'nov1-22',
    skill: 'Perimeter',
    ao: 2,
    chapter: 23,
    prompt: 'A rectangle is $13\\,\\text{cm}$ by $7\\,\\text{cm}$. Find its perimeter in centimetres.',
    marks: 2,
    answer: '40',
    solution: ['$2(13+7)=40$.'],
  }),
  numeric({
    id: 'nov1-23',
    skill: 'Scale',
    ao: 2,
    chapter: 20,
    prompt: 'A scale drawing uses $1\\,\\text{cm}$ to represent $4\\,\\text{m}$. A wall is $18\\,\\text{m}$ long. How long is it on the drawing, in centimetres?',
    marks: 2,
    answer: '4.5',
    solution: ['$18 \\div 4 = 4.5$ cm.'],
  }),
  numeric({
    id: 'nov1-24',
    skill: 'FDP',
    ao: 1,
    chapter: 6,
    prompt: 'Write $\\dfrac{3}{5}$ as a percentage.',
    marks: 1,
    answer: '60',
    accepted: ['60%'],
    solution: ['$\\dfrac{3}{5} = 0.6 = 60\\%$.'],
  }),
  multi({
    id: 'nov1-16',
    skill: 'Simultaneous',
    ao: 2,
    chapter: 16,
    tier: 'H',
    prompt: 'Solve $3x + 2y = 16$ and $x - 2y = 0$.',
    parts: [
      {
        id: 'nov1-16a',
        label: 'a',
        prompt: 'Find $x$.',
        marks: 2,
        answer: '4',
        solution: ['Add: $4x = 16$, so $x = 4$.'],
      },
      {
        id: 'nov1-16b',
        label: 'b',
        prompt: 'Find $y$.',
        marks: 2,
        answer: '2',
        solution: ['From $x-2y=0$: $4-2y=0$, so $y=2$.'],
      },
    ],
  }),
  numeric({
    id: 'nov1-17',
    skill: 'Indices',
    ao: 1,
    chapter: 7,
    tier: 'H',
    prompt: 'Simplify $\\dfrac{5^8}{5^3}$. Give your answer as a power of 5.',
    marks: 2,
    answer: '5^5',
    accepted: ['3125'],
    placeholder: 'e.g. 5^5',
    solution: ['Subtract the indices: $5^{8-3} = 5^5$.'],
  }),
  numeric({
    id: 'nov1-18',
    skill: 'Graphs',
    ao: 3,
    chapter: 15,
    tier: 'H',
    prompt: 'The line $y = -2x + 7$ meets the $y$-axis at $(0, c)$. What is $c$?',
    marks: 2,
    answer: '7',
    solution: ['When $x=0$, $y=7$.'],
  }),
]

const paper2 = [
  numeric({
    id: 'nov2-1',
    skill: 'Reverse percentages',
    ao: 2,
    chapter: 5,
    prompt: 'A shop sells a blender for £52.80 after adding $20\\%$ VAT. What was the price before VAT, in pounds?',
    marks: 3,
    answer: '44',
    accepted: ['44.00'],
    solution: ['£52.80 is $120\\%$ of the pre-VAT price. $52.80 \\div 1.2 = 44$.'],
  }),
  numeric({
    id: 'nov2-2',
    skill: 'Compound interest',
    ao: 2,
    chapter: 5,
    prompt: '£2000 is invested at $3\\%$ compound interest for 3 years. Find the value after 3 years, in pounds, to the nearest penny.',
    marks: 4,
    answer: '2185.45',
    tolerance: 0.02,
    solution: ['$2000 \\times 1.03^3 = 2000 \\times 1.092727 = 2185.45$.'],
  }),
  multi({
    id: 'nov2-3',
    skill: 'Trigonometry',
    ao: 2,
    chapter: 25,
    prompt:
      'In right-angled triangle $ABC$, $\\angle C = 90^\\circ$, $AC = 8\\,\\text{cm}$ and $BC = 15\\,\\text{cm}$.',
    parts: [
      {
        id: 'nov2-3a',
        label: 'a',
        prompt: 'Find $AB$, in centimetres.',
        marks: 2,
        answer: '17',
        solution: ['$8^2 + 15^2 = 64 + 225 = 289$. $AB = \\sqrt{289} = 17$.'],
      },
      {
        id: 'nov2-3b',
        label: 'b',
        prompt: 'Find $\\angle BAC$ in degrees, to 1 decimal place.',
        marks: 3,
        answer: '61.9',
        tolerance: 0.15,
        solution: ['$\\tan A = \\dfrac{15}{8} = 1.875$. $A = \\tan^{-1}(1.875) = 61.9^\\circ$ (1 d.p.).'],
      },
    ],
  }),
  multi({
    id: 'nov2-4',
    skill: 'Circles',
    ao: 2,
    chapter: 27,
    prompt: 'A circle has radius $7\\,\\text{cm}$. Use $\\pi = 3.14$ if you do not have $\\pi$ on your calculator.',
    parts: [
      {
        id: 'nov2-4a',
        label: 'a',
        prompt: 'Find the circumference, to 1 decimal place.',
        marks: 2,
        answer: '44.0',
        accepted: ['43.98', '44'],
        tolerance: 0.2,
        solution: ['$C = 2\\pi r = 14\\pi \\approx 43.98$, which is $44.0$ to 1 d.p.'],
      },
      {
        id: 'nov2-4b',
        label: 'b',
        prompt: 'Find the area, to the nearest whole number.',
        marks: 2,
        answer: '154',
        accepted: ['153.9'],
        tolerance: 1,
        solution: ['$A = \\pi r^2 = 49\\pi \\approx 153.9$, which is $154$ to the nearest integer.'],
      },
    ],
  }),
  numeric({
    id: 'nov2-5',
    skill: 'Density',
    ao: 3,
    chapter: 19,
    prompt: 'Olive oil has density $0.92\\,\\text{g/cm}^3$. What is the mass, in grams, of $250\\,\\text{cm}^3$?',
    marks: 3,
    answer: '230',
    solution: ['Mass $=$ density $\\times$ volume $= 0.92 \\times 250 = 230$ g.'],
  }),
  multi({
    id: 'nov2-6',
    skill: 'Averages',
    ao: 2,
    chapter: 30,
    prompt: 'A frequency table for waiting times (minutes) is: 0–4 (6 people), 5–9 (10 people), 10–14 (4 people).',
    parts: [
      {
        id: 'nov2-6a',
        label: 'a',
        prompt: 'How many people were surveyed?',
        marks: 1,
        answer: '20',
        solution: ['$6+10+4=20$.'],
      },
      {
        id: 'nov2-6b',
        label: 'b',
        prompt: 'Estimate the mean waiting time, in minutes.',
        marks: 4,
        answer: '6.5',
        accepted: ['13/2'],
        tolerance: 0.05,
        solution: [
          'Midpoints 2, 7 and 12.',
          'Total $= 6\\times 2 + 10\\times 7 + 4\\times 12 = 12+70+48=130$.',
          'Mean $= 130 \\div 20 = 6.5$.',
        ],
      },
    ],
  }),
  numeric({
    id: 'nov2-7',
    skill: 'Speed',
    ao: 2,
    chapter: 19,
    prompt: 'A train travels $175\\,\\text{km}$ at an average speed of $70\\,\\text{km/h}$. How many minutes does the journey take?',
    marks: 3,
    answer: '150',
    solution: ['Time $= 175 \\div 70 = 2.5$ hours $= 150$ minutes.'],
  }),
  numeric({
    id: 'nov2-8',
    skill: 'Scale',
    ao: 2,
    chapter: 20,
    prompt: 'A model boat is made to a scale of $1:40$. The model is $28\\,\\text{cm}$ long. How long is the real boat, in metres?',
    marks: 3,
    answer: '11.2',
    solution: ['Real length $= 28 \\times 40 = 1120\\,\\text{cm} = 11.2\\,\\text{m}$.'],
  }),
  numeric({
    id: 'nov2-9',
    skill: 'Volume',
    ao: 2,
    chapter: 23,
    prompt: 'A cuboid measures $4.5\\,\\text{cm}$ by $3.2\\,\\text{cm}$ by $2.5\\,\\text{cm}$. Find its volume in cm$^3$.',
    marks: 3,
    answer: '36',
    tolerance: 0.05,
    solution: ['$4.5 \\times 3.2 \\times 2.5 = 36$.'],
  }),
  mc({
    id: 'nov2-10',
    skill: 'Transformations',
    ao: 1,
    chapter: 26,
    prompt: 'Shape A is mapped onto shape B by a translation with vector $\\begin{pmatrix} 3 \\\\ -5 \\end{pmatrix}$. Which statement is true?',
    marks: 2,
    choices: [
      'A moves 3 right and 5 up',
      'A moves 3 right and 5 down',
      'A moves 3 left and 5 down',
      'A moves 5 right and 3 down',
    ],
    correctIndex: 1,
    solution: ['The vector $\\begin{pmatrix} 3 \\\\ -5 \\end{pmatrix}$ means 3 units right and 5 units down.'],
  }),
  numeric({
    id: 'nov2-11',
    skill: 'Formulae',
    ao: 1,
    chapter: 12,
    prompt: 'The surface area of a cube is $A = 6s^2$. Find $A$ when $s = 4.5$.',
    marks: 2,
    answer: '121.5',
    tolerance: 0.05,
    solution: ['$6 \\times 4.5^2 = 6 \\times 20.25 = 121.5$.'],
  }),
  numeric({
    id: 'nov2-12',
    skill: 'FDP',
    ao: 1,
    chapter: 6,
    prompt: 'Write $37.5\\%$ as a fraction in its lowest terms.',
    marks: 2,
    answer: '3/8',
    solution: ['$37.5\\% = \\dfrac{375}{1000} = \\dfrac{3}{8}$.'],
  }),
  numeric({
    id: 'nov2-13',
    skill: 'Probability',
    ao: 3,
    chapter: 28,
    prompt:
      'A spinner is biased. $P(\\text{red}) = 0.35$ and $P(\\text{blue}) = 0.4$. The rest of the outcomes are green. Find $P(\\text{green})$.',
    marks: 2,
    answer: '0.25',
    accepted: ['1/4'],
    solution: ['$1 - 0.35 - 0.4 = 0.25$.'],
  }),
  numeric({
    id: 'nov2-18',
    skill: 'Percentages',
    ao: 1,
    chapter: 5,
    prompt: 'Work out $17.5\\%$ of 80.',
    marks: 2,
    answer: '14',
    solution: ['$10\\% = 8$, $5\\% = 4$, $2.5\\% = 2$. Total $14$.'],
  }),
  numeric({
    id: 'nov2-19',
    skill: 'Expressions',
    ao: 1,
    chapter: 9,
    prompt: 'If $x = 6$, find the value of $x^2 - 5x + 4$.',
    marks: 2,
    answer: '10',
    solution: ['$36 - 30 + 4 = 10$.'],
  }),
  numeric({
    id: 'nov2-20',
    skill: 'Ratio',
    ao: 2,
    chapter: 17,
    prompt: 'Share 84 in the ratio $5 : 7$. What is the larger share?',
    marks: 2,
    answer: '49',
    solution: ['Parts total 12. Larger share $\\dfrac{7}{12} \\times 84 = 49$.'],
  }),
  numeric({
    id: 'nov2-21',
    skill: 'Perimeter',
    ao: 2,
    chapter: 23,
    prompt: 'An equilateral triangle has perimeter $27\\,\\text{cm}$. Find the length of one side.',
    marks: 2,
    answer: '9',
    solution: ['$27 \\div 3 = 9$.'],
  }),
  numeric({
    id: 'nov2-22',
    skill: 'Decimals',
    ao: 1,
    chapter: 6,
    prompt: 'Work out $15.6 \\div 1.2$.',
    marks: 2,
    answer: '13',
    solution: ['$156 \\div 12 = 13$.'],
  }),
  numeric({
    id: 'nov2-14',
    skill: 'Standard form',
    ao: 1,
    chapter: 8,
    tier: 'H',
    prompt: 'Work out $(6.4 \\times 10^5) + (8.1 \\times 10^4)$. Give your answer in standard form.',
    marks: 3,
    answer: '7.21 x 10^5',
    accepted: ['7.21×10^5', '7.21e5', '721000'],
    placeholder: 'e.g. 7.21 x 10^5',
    solution: ['$8.1 \\times 10^4 = 0.81 \\times 10^5$. Sum $= 7.21 \\times 10^5$.'],
  }),
  numeric({
    id: 'nov2-15',
    skill: 'Rearranging',
    ao: 2,
    chapter: 12,
    tier: 'H',
    prompt: 'Make $r$ the subject of $A = 4\\pi r^2$. Write an expression such as sqrt(A/(4pi)).',
    marks: 3,
    answer: 'sqrt(A/(4pi))',
    accepted: ['sqrt(A/(4π))', '√(A/(4π))', 'sqrt(A/4pi)'],
    placeholder: 'e.g. sqrt(A/(4pi))',
    solution: ['$r^2 = \\dfrac{A}{4\\pi}$, so $r = \\sqrt{\\dfrac{A}{4\\pi}}$ (taking the positive root).'],
  }),
  numeric({
    id: 'nov2-16',
    skill: 'Trigonometry',
    ao: 3,
    chapter: 25,
    tier: 'H',
    prompt:
      'A ladder $6.5\\,\\text{m}$ long leans against a wall. The foot is $2.4\\,\\text{m}$ from the wall. How high up the wall does the ladder reach, in metres, to 1 decimal place?',
    marks: 3,
    answer: '6.0',
    accepted: ['6', '6.04'],
    tolerance: 0.15,
    solution: ['$h = \\sqrt{6.5^2 - 2.4^2} = \\sqrt{42.25 - 5.76} = \\sqrt{36.49} = 6.04$, so $6.0$ to 1 d.p.'],
  }),
]

const paper3 = [
  multi({
    id: 'nov3-1',
    skill: 'Percentages',
    ao: 3,
    chapter: 5,
    prompt: 'A phone was £360. In March it rose by $15\\%$. In April it then fell by $15\\%$.',
    parts: [
      {
        id: 'nov3-1a',
        label: 'a',
        prompt: 'Find the March price, in pounds.',
        marks: 2,
        answer: '414',
        solution: ['$360 \\times 1.15 = 414$.'],
      },
      {
        id: 'nov3-1b',
        label: 'b',
        prompt: 'Find the April price, in pounds.',
        marks: 2,
        answer: '351.9',
        accepted: ['351.90'],
        tolerance: 0.05,
        solution: ['$414 \\times 0.85 = 351.90$. A rise and fall of $15\\%$ do not cancel.'],
      },
    ],
  }),
  numeric({
    id: 'nov3-2',
    skill: 'Ratio',
    ao: 3,
    chapter: 17,
    prompt:
      'Ali, Bea and Cai share £480 in the ratio $2 : 3 : 7$. Cai gives Bea £40 from his share. How much does Bea have then, in pounds?',
    marks: 4,
    answer: '160',
    solution: [
      'Parts $12$. One part $£40$. Bea first has $3 \\times 40 = 120$.',
      'After the gift Bea has $120 + 40 = 160$.',
    ],
  }),
  multi({
    id: 'nov3-3',
    skill: 'Algebra',
    ao: 1,
    chapter: 11,
    prompt: 'Solve these equations.',
    parts: [
      {
        id: 'nov3-3a',
        label: 'a',
        prompt: 'Solve $7 - 2x = 15$.',
        marks: 2,
        answer: '-4',
        solution: ['$-2x = 8$, so $x = -4$.'],
      },
      {
        id: 'nov3-3b',
        label: 'b',
        prompt: 'Solve $3(x+4) = 2x + 19$.',
        marks: 3,
        answer: '7',
        solution: ['$3x+12=2x+19$, so $x=7$.'],
      },
    ],
  }),
  numeric({
    id: 'nov3-4',
    skill: 'Pythagoras',
    ao: 3,
    chapter: 24,
    prompt:
      'A rectangular field is $60\\,\\text{m}$ by $25\\,\\text{m}$. How long is a diagonal path across the field, in metres?',
    marks: 3,
    answer: '65',
    solution: ['$60^2 + 25^2 = 3600 + 625 = 4225$. Diagonal $= \\sqrt{4225} = 65$.'],
  }),
  multi({
    id: 'nov3-5',
    skill: 'Probability',
    ao: 3,
    chapter: 29,
    prompt:
      'A fair spinner has sections 1, 2, 3 and 4. It is spun twice. The two scores are added.',
    parts: [
      {
        id: 'nov3-5a',
        label: 'a',
        prompt: 'How many equally likely outcomes are there?',
        marks: 1,
        answer: '16',
        solution: ['$4 \\times 4 = 16$ pairs.'],
      },
      {
        id: 'nov3-5b',
        label: 'b',
        prompt: 'Find the probability that the total is 5. Give your answer as a fraction.',
        marks: 3,
        answer: '1/4',
        accepted: ['4/16'],
        solution: ['Totals of 5: $(1,4), (2,3), (3,2), (4,1)$ — 4 outcomes. Probability $\\dfrac{4}{16} = \\dfrac{1}{4}$.'],
      },
    ],
  }),
  numeric({
    id: 'nov3-6',
    skill: 'Circles',
    ao: 3,
    chapter: 27,
    prompt:
      'A circular pond has diameter $10\\,\\text{m}$. A path $1\\,\\text{m}$ wide surrounds it. Find the area of the path, in m$^2$, to 1 decimal place. Use $\\pi = 3.142$.',
    marks: 4,
    answer: '34.6',
    accepted: ['34.56'],
    tolerance: 0.3,
    solution: [
      'Outer radius $6\\,\\text{m}$, inner radius $5\\,\\text{m}$.',
      'Area $= \\pi(36-25) = 11\\pi \\approx 34.56$, so $34.6$ to 1 d.p.',
    ],
  }),
  numeric({
    id: 'nov3-7',
    skill: 'Compound measures',
    ao: 2,
    chapter: 19,
    prompt: 'Pressure $= \\dfrac{\\text{force}}{\\text{area}}$. A force of $840\\,\\text{N}$ acts on an area of $0.35\\,\\text{m}^2$. Find the pressure in N/m$^2$.',
    marks: 2,
    answer: '2400',
    solution: ['$840 \\div 0.35 = 2400$.'],
  }),
  numeric({
    id: 'nov3-8',
    skill: 'Sequences',
    ao: 2,
    chapter: 14,
    prompt: 'The first four terms of a sequence are $18, 13, 8, 3$. Find the $n$th term.',
    marks: 3,
    answer: '23-5n',
    accepted: ['-5n+23', '23 - 5n'],
    solution: ['Difference $-5$, so $-5n + c$. When $n=1$, $-5+c=18$ and $c=23$. $n$th term $23-5n$.'],
  }),
  numeric({
    id: 'nov3-9',
    skill: 'Volume',
    ao: 2,
    chapter: 23,
    prompt:
      'A prism has a cross-section that is a trapezium with parallel sides $6\\,\\text{cm}$ and $10\\,\\text{cm}$ and height $4\\,\\text{cm}$. The prism is $12\\,\\text{cm}$ long. Find its volume in cm$^3$.',
    marks: 4,
    answer: '384',
    solution: [
      'Trapezium area $= \\dfrac{1}{2}(6+10)\\times 4 = 32$.',
      'Volume $= 32 \\times 12 = 384$.',
    ],
  }),
  numeric({
    id: 'nov3-10',
    skill: 'Averages',
    ao: 2,
    chapter: 30,
    prompt: 'The mean of four numbers is 11. Three of the numbers are 8, 9 and 15. Find the fourth number.',
    marks: 3,
    answer: '12',
    solution: ['Total $= 4 \\times 11 = 44$. Fourth number $44 - (8+9+15) = 12$.'],
  }),
  numeric({
    id: 'nov3-11',
    skill: 'Indices',
    ao: 1,
    chapter: 7,
    prompt: 'Work out $3^2 + 4^2 + 12^2$.',
    marks: 2,
    answer: '169',
    solution: ['$9 + 16 + 144 = 169$.'],
  }),
  numeric({
    id: 'nov3-12',
    skill: 'Inequalities',
    ao: 1,
    chapter: 13,
    prompt: 'List the integers that satisfy $-2 < n \\le 3$. Write them in order, separated by commas.',
    marks: 2,
    answer: '-1,0,1,2,3',
    accepted: ['-1, 0, 1, 2, 3'],
    solution: ['Integers strictly greater than $-2$ and at most 3 are $-1, 0, 1, 2, 3$.'],
  }),
  numeric({
    id: 'nov3-13',
    skill: 'Enlargement',
    ao: 2,
    chapter: 26,
    prompt:
      'A photograph is $8\\,\\text{cm}$ by $6\\,\\text{cm}$. It is enlarged by scale factor 2.5. Find the area of the enlargement, in cm$^2$.',
    marks: 3,
    answer: '300',
    solution: ['New sides $20\\,\\text{cm}$ by $15\\,\\text{cm}$. Area $300$. (Area scale factor $2.5^2 = 6.25$, and $48 \\times 6.25 = 300$.)'],
  }),
  numeric({
    id: 'nov3-17',
    skill: 'Fractions',
    ao: 1,
    chapter: 4,
    prompt: 'Work out $1 - \\dfrac{3}{8}$.',
    marks: 2,
    answer: '5/8',
    solution: ['$\\dfrac{8}{8} - \\dfrac{3}{8} = \\dfrac{5}{8}$.'],
  }),
  numeric({
    id: 'nov3-18',
    skill: 'Percentages',
    ao: 2,
    chapter: 5,
    prompt: 'Decrease 90 by $30\\%$.',
    marks: 2,
    answer: '63',
    solution: ['$30\\%$ of 90 is 27, so $90-27=63$.'],
  }),
  numeric({
    id: 'nov3-19',
    skill: 'Directed numbers',
    ao: 1,
    chapter: 2,
    prompt: 'Work out $-4 \\times -7 + 6$.',
    marks: 2,
    answer: '34',
    solution: ['$-4 \\times -7 = 28$, then $28+6=34$.'],
  }),
  numeric({
    id: 'nov3-20',
    skill: 'Angles',
    ao: 2,
    chapter: 21,
    prompt: 'Two angles on a straight line are $3x$ and $x + 20$. Find $x$.',
    marks: 3,
    answer: '40',
    solution: ['$3x + x + 20 = 180$, so $4x = 160$ and $x = 40$.'],
  }),
  numeric({
    id: 'nov3-21',
    skill: 'Rounding',
    ao: 1,
    chapter: 1,
    prompt: 'Round $6.847$ to 2 decimal places.',
    marks: 1,
    answer: '6.85',
    solution: ['The third decimal digit is 7, so 6.847 rounds up to 6.85.'],
  }),
  numeric({
    id: 'nov3-14',
    skill: 'Simultaneous',
    ao: 3,
    chapter: 16,
    tier: 'H',
    prompt:
      'Cinema tickets cost £$x$ for an adult and £$y$ for a child. 3 adults and 2 children cost £32. 1 adult and 4 children cost £24. Find the cost of one adult ticket, in pounds.',
    marks: 4,
    answer: '8',
    solution: [
      '$3x+2y=32$ and $x+4y=24$.',
      'From the second, $x=24-4y$. Substitute: $3(24-4y)+2y=32$, so $72-12y+2y=32$, $72-10y=32$, $y=4$.',
      'Then $x=24-16=8$.',
    ],
  }),
  numeric({
    id: 'nov3-15',
    skill: 'Standard form',
    ao: 2,
    chapter: 8,
    tier: 'H',
    prompt: 'A bacterium is $4 \\times 10^{-6}\\,\\text{m}$ long. How many would stretch $2\\,\\text{cm}$ if placed end to end?',
    marks: 3,
    answer: '5000',
    solution: ['$2\\,\\text{cm} = 0.02\\,\\text{m} = 2 \\times 10^{-2}$. Number $= \\dfrac{2\\times 10^{-2}}{4\\times 10^{-6}} = 0.5 \\times 10^{4} = 5000$.'],
  }),
  numeric({
    id: 'nov3-16',
    skill: 'Graphs',
    ao: 3,
    chapter: 15,
    tier: 'H',
    prompt: 'Line $L$ has equation $2y = 6x - 8$. What is the gradient of $L$?',
    marks: 2,
    answer: '3',
    solution: ['$y = 3x - 4$, so the gradient is 3.'],
  }),
]

export const novemberExam: ExamMock = {
  id: 'november',
  title: 'November mock',
  subtitle: 'Y11 autumn · almost full spec',
  focus:
    'Three 90-minute papers in AQA/Edexcel shape. Paper 1 is non-calculator; Papers 2 and 3 allow a calculator. Slightly thinner than a board paper, original questions only.',
  stage: 'november',
  papers: [
    { id: 'paper-1', title: 'Paper 1', calculator: 'non-calc', durationMinutes: 90, questions: paper1 },
    { id: 'paper-2', title: 'Paper 2', calculator: 'calc', durationMinutes: 90, questions: paper2 },
    { id: 'paper-3', title: 'Paper 3', calculator: 'calc', durationMinutes: 90, questions: paper3 },
  ],
}
