import { multi, numeric } from '../make'
import type { ExamMock } from '../../lib/types'

const paper1 = [
  multi({
    id: 'y10p1-1',
    skill: 'Place value',
    ao: 1,
    chapter: 1,
    prompt: 'This question is about place value and rounding.',
    parts: [
      {
        id: 'y10p1-1a',
        label: 'a',
        prompt: 'Write $4.208 \\times 100$ as an ordinary number.',
        marks: 1,
        answer: '420.8',
        solution: ['Multiplying by 100 moves the digits two places left: $420.8$.'],
      },
      {
        id: 'y10p1-1b',
        label: 'b',
        prompt: 'Round $36\\,472$ to the nearest hundred.',
        marks: 2,
        answer: '36500',
        accepted: ['36,500', '36 500'],
        solution: ['The tens digit is 7, so $36\\,472$ rounds up to $36\\,500$.'],
      },
    ],
  }),
  multi({
    id: 'y10p1-2',
    skill: 'Number facts',
    ao: 1,
    chapter: 3,
    prompt: 'Work with directed numbers and factors.',
    parts: [
      {
        id: 'y10p1-2a',
        label: 'a',
        prompt: 'Work out $-15 + 8 \\times -2$.',
        marks: 2,
        answer: '-31',
        solution: ['Multiply first: $8 \\times -2 = -16$. Then $-15 + -16 = -31$.'],
      },
      {
        id: 'y10p1-2b',
        label: 'b',
        prompt: 'Find the highest common factor of 48 and 72.',
        marks: 2,
        answer: '24',
        solution: ['$48 = 2^4 \\times 3$ and $72 = 2^3 \\times 3^2$. HCF $= 2^3 \\times 3 = 24$.'],
      },
    ],
  }),
  multi({
    id: 'y10p1-3',
    skill: 'Fractions',
    ao: 1,
    chapter: 4,
    prompt: 'Calculate with fractions.',
    parts: [
      {
        id: 'y10p1-3a',
        label: 'a',
        prompt: 'Work out $\\dfrac{2}{3} + \\dfrac{5}{12}$. Give your answer as a mixed number or top-heavy fraction.',
        marks: 2,
        answer: '13/12',
        accepted: ['1 1/12', '1.083'],
        solution: ['$\\dfrac{8}{12} + \\dfrac{5}{12} = \\dfrac{13}{12}$.'],
      },
      {
        id: 'y10p1-3b',
        label: 'b',
        prompt: 'Find $\\dfrac{3}{4}$ of 56.',
        marks: 2,
        answer: '42',
        solution: ['$56 \\div 4 \\times 3 = 42$.'],
      },
    ],
  }),
  numeric({
    id: 'y10p1-4',
    skill: 'Indices',
    ao: 1,
    chapter: 7,
    prompt: 'Simplify $2^3 \\times 2^4$. Give your answer as a power of 2, such as $2^7$.',
    marks: 2,
    answer: '2^7',
    accepted: ['128'],
    placeholder: 'e.g. 2^7',
    solution: ['Add the indices: $2^{3+4} = 2^7$.'],
  }),
  multi({
    id: 'y10p1-5',
    skill: 'Percentages',
    ao: 2,
    chapter: 5,
    prompt: 'A club has 240 members.',
    parts: [
      {
        id: 'y10p1-5a',
        label: 'a',
        prompt: 'Work out $15\\%$ of 240.',
        marks: 2,
        answer: '36',
        solution: ['$10\\% = 24$ and $5\\% = 12$, so $15\\% = 36$.'],
      },
      {
        id: 'y10p1-5b',
        label: 'b',
        prompt: 'The membership fee of £80 is increased by $20\\%$. What is the new fee in pounds?',
        marks: 2,
        answer: '96',
        solution: ['$20\\%$ of 80 is 16, so the new fee is $80 + 16 = 96$.'],
      },
    ],
  }),
  multi({
    id: 'y10p1-6',
    skill: 'Ratio',
    ao: 2,
    chapter: 17,
    prompt: '£210 is shared in the ratio $2 : 3 : 5$.',
    parts: [
      {
        id: 'y10p1-6a',
        label: 'a',
        prompt: 'How much does the smallest share receive, in pounds?',
        marks: 2,
        answer: '42',
        solution: ['Parts total $2+3+5=10$. One part is $210 \\div 10 = 21$. Smallest share $2 \\times 21 = 42$.'],
      },
      {
        id: 'y10p1-6b',
        label: 'b',
        prompt: 'How much more does the largest share receive than the smallest, in pounds?',
        marks: 2,
        answer: '63',
        solution: ['Largest share $5 \\times 21 = 105$. Difference $105 - 42 = 63$.'],
      },
    ],
  }),
  multi({
    id: 'y10p1-7',
    skill: 'Algebra',
    ao: 1,
    chapter: 11,
    prompt: 'This question is about expressions and equations.',
    parts: [
      {
        id: 'y10p1-7a',
        label: 'a',
        prompt: 'Expand $3(2x - 5)$.',
        marks: 1,
        answer: '6x-15',
        accepted: ['6x - 15'],
        solution: ['$3 \\times 2x = 6x$ and $3 \\times -5 = -15$.'],
      },
      {
        id: 'y10p1-7b',
        label: 'b',
        prompt: 'Factorise $12y + 18$.',
        marks: 2,
        answer: '6(2y+3)',
        accepted: ['6(2y + 3)'],
        solution: ['HCF is 6: $6(2y + 3)$.'],
      },
      {
        id: 'y10p1-7c',
        label: 'c',
        prompt: 'Solve $5x - 7 = 3x + 9$.',
        marks: 2,
        answer: '8',
        solution: ['Subtract $3x$: $2x - 7 = 9$. Add 7: $2x = 16$. So $x = 8$.'],
      },
    ],
  }),
  multi({
    id: 'y10p1-8',
    skill: 'Sequences',
    ao: 2,
    chapter: 14,
    prompt: 'A linear sequence begins $5, 9, 13, 17, \\ldots$',
    parts: [
      {
        id: 'y10p1-8a',
        label: 'a',
        prompt: 'Write an expression for the $n$th term.',
        marks: 2,
        answer: '4n+1',
        accepted: ['4n + 1'],
        solution: ['Common difference 4, so $4n + c$. When $n=1$, $4+c=5$ so $c=1$. The $n$th term is $4n+1$.'],
      },
      {
        id: 'y10p1-8b',
        label: 'b',
        prompt: 'Find the 20th term.',
        marks: 1,
        answer: '81',
        solution: ['$4 \\times 20 + 1 = 81$.'],
      },
    ],
  }),
  numeric({
    id: 'y10p1-9',
    skill: 'Angles',
    ao: 2,
    chapter: 21,
    prompt:
      'An isosceles triangle has a vertex angle of $70^\\circ$. The two base angles are equal. Work out a base angle.',
    marks: 3,
    answer: '55',
    solution: [
      'The three angles sum to $180^\\circ$.',
      'Base angles total $180 - 70 = 110$.',
      'Each base angle is $110 \\div 2 = 55^\\circ$.',
    ],
  }),
  multi({
    id: 'y10p1-10',
    skill: 'Area',
    ao: 3,
    chapter: 23,
    prompt:
      'A rectangular card measures $10\\,\\text{cm}$ by $6\\,\\text{cm}$. A $4\\,\\text{cm}$ by $3\\,\\text{cm}$ rectangle is cut from one corner.',
    parts: [
      {
        id: 'y10p1-10a',
        label: 'a',
        prompt: 'Find the remaining area, in cm$^2$.',
        marks: 3,
        answer: '48',
        solution: ['Large rectangle $10 \\times 6 = 60$. Cut-out $4 \\times 3 = 12$. Remaining $60-12=48$.'],
      },
      {
        id: 'y10p1-10b',
        label: 'b',
        prompt: 'The remaining card is a prism of thickness $2\\,\\text{cm}$. Find its volume, in cm$^3$.',
        marks: 2,
        answer: '96',
        solution: ['Volume $=$ area of cross-section $\\times$ thickness $= 48 \\times 2 = 96$.'],
      },
    ],
  }),
  numeric({
    id: 'y10p1-11',
    skill: 'Proportion',
    ao: 3,
    chapter: 18,
    prompt: 'A recipe for 8 people uses $360\\,\\text{g}$ of flour. How many grams are needed for 6 people?',
    marks: 3,
    answer: '270',
    solution: ['One person uses $360 \\div 8 = 45\\,\\text{g}$. Six people need $45 \\times 6 = 270\\,\\text{g}$.'],
  }),
  numeric({
    id: 'y10p1-14',
    skill: 'Decimals',
    ao: 1,
    chapter: 6,
    prompt: 'Work out $7.2 \\div 0.3$.',
    marks: 2,
    answer: '24',
    solution: ['$72 \\div 3 = 24$.'],
  }),
  numeric({
    id: 'y10p1-15',
    skill: 'Expressions',
    ao: 1,
    chapter: 9,
    prompt: 'Simplify $6x - 2x + 5$.',
    marks: 1,
    answer: '4x+5',
    accepted: ['4x + 5'],
    solution: ['$6x-2x=4x$, so $4x+5$.'],
  }),
  numeric({
    id: 'y10p1-16',
    skill: 'FDP',
    ao: 1,
    chapter: 6,
    prompt: 'Write $\\dfrac{1}{4}$ as a percentage.',
    marks: 1,
    answer: '25',
    accepted: ['25%'],
    solution: ['$\\dfrac{1}{4} = 0.25 = 25\\%$.'],
  }),
  numeric({
    id: 'y10p1-12',
    skill: 'Inequalities',
    ao: 1,
    chapter: 13,
    tier: 'H',
    prompt: 'Solve $3x + 5 > 17$. Give the critical value that $x$ is greater than.',
    marks: 3,
    answer: '4',
    solution: ['Subtract 5: $3x > 12$. Divide by 3: $x > 4$.'],
  }),
  multi({
    id: 'y10p1-13',
    skill: 'Simultaneous',
    ao: 2,
    chapter: 16,
    tier: 'H',
    prompt: 'Solve the simultaneous equations $2x + y = 11$ and $x - y = 1$.',
    parts: [
      {
        id: 'y10p1-13a',
        label: 'a',
        prompt: 'Find $x$.',
        marks: 2,
        answer: '4',
        solution: ['Add the equations: $3x = 12$, so $x = 4$.'],
      },
      {
        id: 'y10p1-13b',
        label: 'b',
        prompt: 'Find $y$.',
        marks: 2,
        answer: '3',
        solution: ['From $x - y = 1$: $4 - y = 1$, so $y = 3$.'],
      },
    ],
  }),
]

const paper2 = [
  multi({
    id: 'y10p2-1',
    skill: 'Decimals',
    ao: 1,
    chapter: 6,
    prompt: 'Calculate with decimals and convert between forms.',
    parts: [
      {
        id: 'y10p2-1a',
        label: 'a',
        prompt: 'Work out $3.6 \\times 1.25$.',
        marks: 2,
        answer: '4.5',
        solution: ['$36 \\times 125 = 4500$, then 3 decimal places altogether gives $4.500 = 4.5$.'],
      },
      {
        id: 'y10p2-1b',
        label: 'b',
        prompt: 'Write $0.375$ as a fraction in its lowest terms.',
        marks: 2,
        answer: '3/8',
        solution: ['$0.375 = \\dfrac{375}{1000} = \\dfrac{3}{8}$.'],
      },
    ],
  }),
  numeric({
    id: 'y10p2-2',
    skill: 'Reverse percentages',
    ao: 2,
    chapter: 5,
    prompt:
      'After a $20\\%$ decrease, a coat costs £64. What was the original price, in pounds?',
    marks: 3,
    answer: '80',
    solution: ['£64 is $80\\%$ of the original. $64 \\div 0.8 = 80$.'],
  }),
  numeric({
    id: 'y10p2-3',
    skill: 'Compound interest',
    ao: 2,
    chapter: 5,
    prompt:
      '£1250 is invested at $4\\%$ compound interest for 2 years. What is the value after 2 years, in pounds?',
    marks: 3,
    answer: '1352',
    accepted: ['1352.00'],
    tolerance: 0.05,
    solution: ['$1250 \\times 1.04^2 = 1250 \\times 1.0816 = 1352$.'],
  }),
  multi({
    id: 'y10p2-4',
    skill: 'Compound measures',
    ao: 2,
    chapter: 19,
    prompt: 'A cyclist travels $27\\,\\text{km}$ in 1 hour 30 minutes.',
    parts: [
      {
        id: 'y10p2-4a',
        label: 'a',
        prompt: 'Work out the average speed in km/h.',
        marks: 2,
        answer: '18',
        solution: ['1 hour 30 minutes is $1.5$ hours. Speed $= 27 \\div 1.5 = 18$ km/h.'],
      },
      {
        id: 'y10p2-4b',
        label: 'b',
        prompt: 'At the same average speed, how many minutes would $12\\,\\text{km}$ take?',
        marks: 2,
        answer: '40',
        solution: ['Time $= 12 \\div 18 = \\dfrac{2}{3}$ hour $= 40$ minutes.'],
      },
    ],
  }),
  numeric({
    id: 'y10p2-5',
    skill: 'Scale',
    ao: 2,
    chapter: 20,
    prompt:
      'A map uses a scale of $1:25\\,000$. Two villages are $4.8\\,\\text{cm}$ apart on the map. How far apart are they in kilometres?',
    marks: 3,
    answer: '1.2',
    solution: [
      '$4.8\\,\\text{cm}$ on the map is $4.8 \\times 25\\,000 = 120\\,000\\,\\text{cm}$.',
      '$120\\,000\\,\\text{cm} = 1200\\,\\text{m} = 1.2\\,\\text{km}$.',
    ],
  }),
  multi({
    id: 'y10p2-6',
    skill: 'Formulae',
    ao: 1,
    chapter: 12,
    prompt: 'The formula $v = u + at$ is used for motion in a straight line.',
    parts: [
      {
        id: 'y10p2-6a',
        label: 'a',
        prompt: 'Find $v$ when $u = 8$, $a = 3$ and $t = 5$.',
        marks: 2,
        answer: '23',
        solution: ['$v = 8 + 3 \\times 5 = 8 + 15 = 23$.'],
      },
      {
        id: 'y10p2-6b',
        label: 'b',
        prompt: 'Rearrange the formula to make $a$ the subject. Write your answer as a formula such as $(v-u)/t$.',
        marks: 2,
        answer: '(v-u)/t',
        accepted: ['(v - u)/t', 'a=(v-u)/t'],
        placeholder: 'e.g. (v-u)/t',
        solution: ['$v - u = at$, so $a = \\dfrac{v-u}{t}$.'],
      },
    ],
  }),
  numeric({
    id: 'y10p2-7',
    skill: 'Graphs',
    ao: 2,
    chapter: 15,
    prompt: 'A straight line passes through $(0, 5)$ and $(4, 13)$. Find the gradient of the line.',
    marks: 3,
    answer: '2',
    solution: ['Gradient $= \\dfrac{13-5}{4-0} = \\dfrac{8}{4} = 2$.'],
  }),
  numeric({
    id: 'y10p2-8',
    skill: 'Volume',
    ao: 2,
    chapter: 23,
    prompt:
      'A triangular prism has a right-angled triangular cross-section with legs $5\\,\\text{cm}$ and $12\\,\\text{cm}$, and length $9\\,\\text{cm}$. Find the volume in cm$^3$.',
    marks: 4,
    answer: '270',
    solution: [
      'Area of triangle $= \\dfrac{1}{2} \\times 5 \\times 12 = 30$.',
      'Volume $= 30 \\times 9 = 270$.',
    ],
  }),
  numeric({
    id: 'y10p2-9',
    skill: 'Inverse proportion',
    ao: 2,
    chapter: 18,
    prompt:
      '6 machines take 8 hours to complete a job. How many hours would 4 identical machines take, working at the same rate?',
    marks: 3,
    answer: '12',
    solution: ['Total machine-hours $= 6 \\times 8 = 48$. Four machines take $48 \\div 4 = 12$ hours.'],
  }),
  numeric({
    id: 'y10p2-10',
    skill: 'Density',
    ao: 3,
    chapter: 19,
    prompt:
      'A metal block has mass $2.4\\,\\text{kg}$ and volume $300\\,\\text{cm}^3$. Find the density in g/cm$^3$.',
    marks: 4,
    answer: '8',
    solution: ['$2.4\\,\\text{kg} = 2400\\,\\text{g}$. Density $= 2400 \\div 300 = 8$ g/cm$^3$.'],
  }),
  numeric({
    id: 'y10p2-11',
    skill: 'Area problem',
    ao: 3,
    chapter: 23,
    prompt:
      'A path $1.5\\,\\text{m}$ wide surrounds a rectangular lawn $12\\,\\text{m}$ by $8\\,\\text{m}$. Find the area of the path, in m$^2$.',
    marks: 4,
    answer: '69',
    solution: [
      'Outer rectangle is $15\\,\\text{m}$ by $11\\,\\text{m}$, area $165$.',
      'Lawn area $12 \\times 8 = 96$.',
      'Path area $165 - 96 = 69$.',
    ],
  }),
  numeric({
    id: 'y10p2-14',
    skill: 'Percentages',
    ao: 1,
    chapter: 5,
    prompt: 'Work out $5\\%$ of 360.',
    marks: 2,
    answer: '18',
    solution: ['$10\\% = 36$, so $5\\% = 18$.'],
  }),
  numeric({
    id: 'y10p2-15',
    skill: 'Linear equations',
    ao: 1,
    chapter: 11,
    prompt: 'Solve $x + 17 = 4x - 4$.',
    marks: 2,
    answer: '7',
    solution: ['$17+4=4x-x$, so $21=3x$ and $x=7$.'],
  }),
  numeric({
    id: 'y10p2-12',
    skill: 'Standard form',
    ao: 1,
    chapter: 8,
    tier: 'H',
    prompt:
      'Work out $(4.5 \\times 10^6) \\div (9 \\times 10^{-2})$. Give your answer in standard form.',
    marks: 3,
    answer: '5 x 10^7',
    accepted: ['5×10^7', '5*10^7', '5e7', '50000000'],
    placeholder: 'e.g. 5 x 10^7',
    solution: ['$4.5 \\div 9 = 0.5$ and $10^{6-(-2)} = 10^8$, so $0.5 \\times 10^8 = 5 \\times 10^7$.'],
  }),
  numeric({
    id: 'y10p2-13',
    skill: 'Graphs',
    ao: 3,
    chapter: 15,
    tier: 'H',
    prompt:
      'The line $y = 3x - 4$ crosses the $x$-axis. What is the $x$-coordinate of the intercept?',
    marks: 3,
    answer: '4/3',
    accepted: ['1.333', '1.33', '1 1/3'],
    tolerance: 0.01,
    solution: ['Set $y=0$: $3x-4=0$, so $3x=4$ and $x=\\dfrac{4}{3}$.'],
  }),
]

export const year10Exam: ExamMock = {
  id: 'year-10',
  title: 'Year 10 mock',
  subtitle: 'Core Chapters 1–23 · Foundation + intro Higher',
  focus:
    'Two thinner papers on number, algebra, ratio and early geometry. Paper 1 is non-calculator; Paper 2 allows a calculator. Original questions written for this practice book.',
  stage: 'year10',
  papers: [
    {
      id: 'paper-1',
      title: 'Paper 1',
      calculator: 'non-calc',
      durationMinutes: 60,
      questions: paper1,
    },
    {
      id: 'paper-2',
      title: 'Paper 2',
      calculator: 'calc',
      durationMinutes: 60,
      questions: paper2,
    },
  ],
}
